/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 18 "program.c"
void __globinit_program(void) ;
extern void __CrestInit(void)  __attribute__((__crest_skip__)) ;
extern void __CrestHandleReturn(int id , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestReturn(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestCall(int id , unsigned int fid )  __attribute__((__crest_skip__)) ;
extern void __CrestBranch(int id , int bid , unsigned char b )  __attribute__((__crest_skip__)) ;
extern void __CrestApply2(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestApply1(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestClearStack(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestStore(int id , unsigned long addr )  __attribute__((__crest_skip__)) ;
extern void __CrestLoad(int id , unsigned long addr , long long val )  __attribute__((__crest_skip__)) ;
#line 362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 431
extern int scanf(char const   * __restrict  __format  , ...)  __asm__("__isoc99_scanf")  ;
#line 5 "program.c"
int f(int b ) 
{ 
  int __retres2 ;

  {
  __CrestCall(2, 1);
  __CrestStore(1, (unsigned long )(& b));
#line 7
  printf((char const   * __restrict  )"F function\n");
  __CrestClearStack(3);
  {
  __CrestLoad(6, (unsigned long )(& b), (long long )b);
  __CrestLoad(5, (unsigned long )0, (long long )20);
  __CrestApply2(4, 14, (long long )(b > 20));
#line 8
  if (b > 20) {
    __CrestBranch(7, 3, 1);
#line 9
    printf((char const   * __restrict  )"b > 20");
    __CrestClearStack(9);
  } else {
    __CrestBranch(8, 4, 0);

  }
  }
  {
#line 11
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(12, (unsigned long )(& b), (long long )b);
    __CrestLoad(11, (unsigned long )0, (long long )10);
    __CrestApply2(10, 16, (long long )(b < 10));
#line 11
    if (b < 10) {
      __CrestBranch(13, 9, 1);

    } else {
      __CrestBranch(14, 10, 0);
#line 11
      goto while_break;
    }
    }
    __CrestLoad(17, (unsigned long )(& b), (long long )b);
    __CrestLoad(16, (unsigned long )0, (long long )1);
    __CrestApply2(15, 0, (long long )(b + 1));
    __CrestStore(18, (unsigned long )(& b));
#line 13
    b ++;
  }
  while_break: /* CIL Label */ ;
  }
  __CrestLoad(19, (unsigned long )0, (long long )0);
  __CrestStore(20, (unsigned long )(& __retres2));
#line 15
  __retres2 = 0;
  {
  __CrestLoad(21, (unsigned long )(& __retres2), (long long )__retres2);
  __CrestReturn(22);
#line 5
  return (__retres2);
  }
}
}
#line 18 "program.c"
int main(void) 
{ 
  int a ;
  int i ;
  int __retres3 ;

  {
  __globinit_program();
  __CrestCall(23, 2);
#line 22
  scanf((char const   * __restrict  )"%d", & a);
  __CrestClearStack(24);
  __CrestLoad(27, (unsigned long )(& a), (long long )a);
  __CrestLoad(26, (unsigned long )0, (long long )100);
  __CrestApply2(25, 14, (long long )(a > 100));
#line 24
  if (a > 100) {
    __CrestBranch(28, 17, 1);
    __CrestLoad(30, (unsigned long )0, (long long )200);
#line 26
    printf((char const   * __restrict  )"Sum is: %d\n", 200);
    __CrestClearStack(31);
    __CrestLoad(32, (unsigned long )(& a), (long long )a);
#line 27
    f(a);
    __CrestClearStack(33);
  } else {
    __CrestBranch(29, 18, 0);
    {
    __CrestLoad(36, (unsigned long )(& a), (long long )a);
    __CrestLoad(35, (unsigned long )0, (long long )200);
    __CrestApply2(34, 14, (long long )(a > 200));
#line 29
    if (a > 200) {
      __CrestBranch(37, 19, 1);
      __CrestLoad(39, (unsigned long )0, (long long )0);
#line 30
      printf((char const   * __restrict  )"Sum is: %d\n", 0);
      __CrestClearStack(40);
    } else {
      __CrestBranch(38, 20, 0);
#line 34
      printf((char const   * __restrict  )"Small number\n");
      __CrestClearStack(41);
    }
    }
  }
  __CrestLoad(44, (unsigned long )(& a), (long long )a);
  __CrestLoad(43, (unsigned long )0, (long long )0);
  __CrestApply2(42, 12, (long long )(a == 0));
#line 39
  if (a == 0) {
    __CrestBranch(45, 23, 1);
#line 39
    goto case_0;
  } else {
    __CrestBranch(46, 24, 0);

  }
  __CrestLoad(49, (unsigned long )(& a), (long long )a);
  __CrestLoad(48, (unsigned long )0, (long long )1);
  __CrestApply2(47, 12, (long long )(a == 1));
#line 42
  if (a == 1) {
    __CrestBranch(50, 26, 1);
#line 42
    goto case_1;
  } else {
    __CrestBranch(51, 27, 0);

  }
#line 45
  goto switch_default;
  case_0: /* CIL Label */ 
#line 40
  printf((char const   * __restrict  )"a=0\n");
  __CrestClearStack(52);
#line 41
  goto switch_break;
  case_1: /* CIL Label */ 
#line 43
  printf((char const   * __restrict  )"a=1\n");
  __CrestClearStack(53);
#line 44
  goto switch_break;
  switch_default: /* CIL Label */ 
#line 46
  printf((char const   * __restrict  )"a!=0 a!=1\n");
  __CrestClearStack(54);
  switch_break: /* CIL Label */ ;
#line 49
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(57, (unsigned long )(& a), (long long )a);
    __CrestLoad(56, (unsigned long )0, (long long )10);
    __CrestApply2(55, 14, (long long )(a > 10));
#line 49
    if (a > 10) {
      __CrestBranch(58, 39, 1);

    } else {
      __CrestBranch(59, 40, 0);
#line 49
      goto while_break;
    }
    }
#line 51
    printf((char const   * __restrict  )"a > 10");
    __CrestClearStack(60);
    __CrestLoad(63, (unsigned long )(& a), (long long )a);
    __CrestLoad(62, (unsigned long )0, (long long )1);
    __CrestApply2(61, 1, (long long )(a - 1));
    __CrestStore(64, (unsigned long )(& a));
#line 52
    a --;
  }
  while_break: /* CIL Label */ 
  __CrestLoad(65, (unsigned long )0, (long long )0);
  __CrestStore(66, (unsigned long )(& i));
#line 55
  i = 0;
#line 55
  while (1) {
    while_continue___0: /* CIL Label */ ;
    {
    __CrestLoad(69, (unsigned long )(& i), (long long )i);
    __CrestLoad(68, (unsigned long )0, (long long )5);
    __CrestApply2(67, 16, (long long )(i < 5));
#line 55
    if (i < 5) {
      __CrestBranch(70, 48, 1);

    } else {
      __CrestBranch(71, 49, 0);
#line 55
      goto while_break___0;
    }
    }
    __CrestLoad(72, (unsigned long )(& i), (long long )i);
#line 56
    printf((char const   * __restrict  )"i=%d ", i);
    __CrestClearStack(73);
    __CrestLoad(76, (unsigned long )(& i), (long long )i);
    __CrestLoad(75, (unsigned long )0, (long long )1);
    __CrestApply2(74, 0, (long long )(i + 1));
    __CrestStore(77, (unsigned long )(& i));
#line 55
    i ++;
  }
  while_break___0: /* CIL Label */ 
  __CrestLoad(78, (unsigned long )0, (long long )0);
  __CrestStore(79, (unsigned long )(& __retres3));
#line 57
  __retres3 = 0;
  __CrestLoad(80, (unsigned long )(& __retres3), (long long )__retres3);
  __CrestReturn(81);
#line 18
  return (__retres3);
}
}
void __globinit_program(void) 
{ 


  {
  __CrestInit();
}
}
