/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

extern int printf(char const   * __restrict  __format  , ...) ;
int glob  ;
int main(void) 
{ 


  {
  if (glob > 1) {
    printf((char const   * __restrict  )"1");
  } else
  if (glob > 7) {
    printf((char const   * __restrict  )"2");
  }
  if (glob > 1) {
    printf((char const   * __restrict  )"1");
  } else {
    printf((char const   * __restrict  )"2");
  }
  return (0);
}
}
