/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 528 "replace.c"
void __globinit_replace(void) ;
extern void __CrestInit(void)  __attribute__((__crest_skip__)) ;
extern void __CrestHandleReturn(int id , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestReturn(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestCall(int id , unsigned int fid )  __attribute__((__crest_skip__)) ;
extern void __CrestBranch(int id , int bid , unsigned char b )  __attribute__((__crest_skip__)) ;
extern void __CrestApply2(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestApply1(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestClearStack(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestStore(int id , unsigned long addr )  __attribute__((__crest_skip__)) ;
extern void __CrestLoad(int id , unsigned long addr , long long val )  __attribute__((__crest_skip__)) ;
#line 131 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
#line 132 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
#line 216 "/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h"
typedef unsigned long size_t;
#line 44 "/usr/include/stdio.h"
struct _IO_FILE;
#line 44
struct _IO_FILE;
#line 48 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
#line 144 "/usr/include/libio.h"
struct _IO_FILE;
#line 150 "/usr/include/libio.h"
typedef void _IO_lock_t;
#line 156 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
#line 241 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
#line 11 "replace.c"
typedef char bool;
#line 40 "replace.c"
typedef char character;
#line 41 "replace.c"
typedef char string[100];
#line 79 "/usr/include/ctype.h"
extern  __attribute__((__nothrow__)) unsigned short const   **( __attribute__((__leaf__)) __ctype_b_loc)(void)  __attribute__((__const__)) ;
#line 169 "/usr/include/stdio.h"
extern struct _IO_FILE *stdout ;
#line 356
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
#line 573
extern int fputc(int __c , FILE *__stream ) ;
#line 515 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) abort)(void) ;
#line 543
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
#line 200 "../../bin/../include/crest.h"
extern void __CrestChar(char *x )  __attribute__((__crest_skip__)) ;
#line 9 "replace.c"
void Caseerror(int n ) ;
#line 43 "replace.c"
bool getline2(char *s , int maxsize ) 
{ 
  int i ;
  char *mem_4 ;
  bool __retres5 ;

  {
  __CrestCall(2, 1);
  __CrestStore(1, (unsigned long )(& maxsize));
  __CrestLoad(3, (unsigned long )0, (long long )0);
  __CrestStore(4, (unsigned long )(& i));
#line 49
  i = 0;
  {
#line 49
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(7, (unsigned long )(& i), (long long )i);
    __CrestLoad(6, (unsigned long )0, (long long )19);
    __CrestApply2(5, 16, (long long )(i < 19));
#line 49
    if (i < 19) {
      __CrestBranch(8, 6, 1);

    } else {
      __CrestBranch(9, 7, 0);
#line 49
      goto while_break;
    }
    }
#line 50
    __CrestChar(s + i);
    __CrestLoad(12, (unsigned long )(& i), (long long )i);
    __CrestLoad(11, (unsigned long )0, (long long )1);
    __CrestApply2(10, 0, (long long )(i + 1));
    __CrestStore(13, (unsigned long )(& i));
#line 49
    i ++;
  }
  while_break: /* CIL Label */ ;
  }
#line 52
  mem_4 = s + i;
  __CrestLoad(14, (unsigned long )0, (long long )((char )'\000'));
  __CrestStore(15, (unsigned long )mem_4);
#line 52
  *mem_4 = (char )'\000';
  __CrestLoad(16, (unsigned long )0, (long long )((bool )1));
  __CrestStore(17, (unsigned long )(& __retres5));
#line 53
  __retres5 = (bool )1;
  {
  __CrestLoad(18, (unsigned long )(& __retres5), (long long )__retres5);
  __CrestReturn(19);
#line 43
  return (__retres5);
  }
}
}
#line 56 "replace.c"
int addstr(char c , char *outset , int *j , int maxset ) 
{ 
  bool result ;
  char *mem_6 ;
  int __retres7 ;

  {
  __CrestCall(22, 2);
  __CrestStore(21, (unsigned long )(& maxset));
  __CrestStore(20, (unsigned long )(& c));
  {
  __CrestLoad(25, (unsigned long )j, (long long )*j);
  __CrestLoad(24, (unsigned long )(& maxset), (long long )maxset);
  __CrestApply2(23, 17, (long long )(*j >= maxset));
#line 64
  if (*j >= maxset) {
    __CrestBranch(26, 14, 1);
    __CrestLoad(28, (unsigned long )0, (long long )((bool )0));
    __CrestStore(29, (unsigned long )(& result));
#line 65
    result = (bool )0;
  } else {
    __CrestBranch(27, 15, 0);
#line 67
    mem_6 = outset + *j;
    __CrestLoad(30, (unsigned long )(& c), (long long )c);
    __CrestStore(31, (unsigned long )mem_6);
#line 67
    *mem_6 = c;
    __CrestLoad(34, (unsigned long )j, (long long )*j);
    __CrestLoad(33, (unsigned long )0, (long long )1);
    __CrestApply2(32, 0, (long long )(*j + 1));
    __CrestStore(35, (unsigned long )j);
#line 68
    (*j) ++;
    __CrestLoad(36, (unsigned long )0, (long long )((bool )1));
    __CrestStore(37, (unsigned long )(& result));
#line 69
    result = (bool )1;
  }
  }
  __CrestLoad(38, (unsigned long )(& result), (long long )result);
  __CrestStore(39, (unsigned long )(& __retres7));
#line 71
  __retres7 = (int )result;
  {
  __CrestLoad(40, (unsigned long )(& __retres7), (long long )__retres7);
  __CrestReturn(41);
#line 56
  return (__retres7);
  }
}
}
#line 74 "replace.c"
char esc(char *s , int *i ) 
{ 
  char result ;
  char *mem_4 ;
  char *mem_5 ;
  char *mem_6 ;
  char *mem_7 ;
  char *mem_8 ;
  char *mem_9 ;

  {
  __CrestCall(42, 3);

  {
#line 80
  mem_4 = s + *i;
  {
  __CrestLoad(45, (unsigned long )mem_4, (long long )*mem_4);
  __CrestLoad(44, (unsigned long )0, (long long )64);
  __CrestApply2(43, 13, (long long )((int )*mem_4 != 64));
#line 80
  if ((int )*mem_4 != 64) {
    __CrestBranch(46, 21, 1);
#line 81
    mem_5 = s + *i;
    __CrestLoad(48, (unsigned long )mem_5, (long long )*mem_5);
    __CrestStore(49, (unsigned long )(& result));
#line 81
    result = *mem_5;
  } else {
    __CrestBranch(47, 22, 0);
    {
#line 83
    mem_6 = s + (*i + 1);
    {
    __CrestLoad(52, (unsigned long )mem_6, (long long )*mem_6);
    __CrestLoad(51, (unsigned long )0, (long long )0);
    __CrestApply2(50, 12, (long long )((int )*mem_6 == 0));
#line 83
    if ((int )*mem_6 == 0) {
      __CrestBranch(53, 25, 1);
      __CrestLoad(55, (unsigned long )0, (long long )((char )'@'));
      __CrestStore(56, (unsigned long )(& result));
#line 84
      result = (char )'@';
    } else {
      __CrestBranch(54, 26, 0);
      __CrestLoad(59, (unsigned long )i, (long long )*i);
      __CrestLoad(58, (unsigned long )0, (long long )1);
      __CrestApply2(57, 0, (long long )(*i + 1));
      __CrestStore(60, (unsigned long )i);
#line 87
      (*i) ++;
      {
#line 88
      mem_7 = s + *i;
      {
      __CrestLoad(63, (unsigned long )mem_7, (long long )*mem_7);
      __CrestLoad(62, (unsigned long )0, (long long )110);
      __CrestApply2(61, 12, (long long )((int )*mem_7 == 110));
#line 88
      if ((int )*mem_7 == 110) {
        __CrestBranch(64, 30, 1);
        __CrestLoad(66, (unsigned long )0, (long long )(char)10);
        __CrestStore(67, (unsigned long )(& result));
#line 89
        result = (char)10;
      } else {
        __CrestBranch(65, 31, 0);
        {
#line 91
        mem_8 = s + *i;
        {
        __CrestLoad(70, (unsigned long )mem_8, (long long )*mem_8);
        __CrestLoad(69, (unsigned long )0, (long long )116);
        __CrestApply2(68, 12, (long long )((int )*mem_8 == 116));
#line 91
        if ((int )*mem_8 == 116) {
          __CrestBranch(71, 34, 1);
          __CrestLoad(73, (unsigned long )0, (long long )(char)9);
          __CrestStore(74, (unsigned long )(& result));
#line 92
          result = (char)9;
        } else {
          __CrestBranch(72, 35, 0);
#line 94
          mem_9 = s + *i;
          __CrestLoad(75, (unsigned long )mem_9, (long long )*mem_9);
          __CrestStore(76, (unsigned long )(& result));
#line 94
          result = *mem_9;
        }
        }
        }
      }
      }
      }
    }
    }
    }
  }
  }
  }
  {
  __CrestLoad(77, (unsigned long )(& result), (long long )result);
  __CrestReturn(78);
#line 96
  return (result);
  }
}
}
#line 99
void change(char *pat , char *sub ) ;
#line 101 "replace.c"
void dodash(char delim , char *src , int *i , char *dest , int *j , int maxset ) 
{ 
  int k ;
  bool junk ;
  char escjunk ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  int tmp___2 ;
  int tmp___3 ;
  unsigned short const   **tmp___4 ;
  unsigned short const   **tmp___5 ;
  char *mem_17 ;
  char *mem_18 ;
  char *mem_19 ;
  char *mem_20 ;
  char *mem_21 ;
  char *mem_22 ;
  char *mem_23 ;
  unsigned short const   *mem_24 ;
  char *mem_25 ;
  unsigned short const   *mem_26 ;
  char *mem_27 ;
  char *mem_28 ;
  char *mem_29 ;
  char *mem_30 ;

  {
  __CrestCall(81, 4);
  __CrestStore(80, (unsigned long )(& maxset));
  __CrestStore(79, (unsigned long )(& delim));
  {
#line 114
  while (1) {
    while_continue: /* CIL Label */ ;
    {
#line 114
    mem_17 = src + *i;
    {
    __CrestLoad(84, (unsigned long )mem_17, (long long )*mem_17);
    __CrestLoad(83, (unsigned long )(& delim), (long long )delim);
    __CrestApply2(82, 13, (long long )((int )*mem_17 != (int )delim));
#line 114
    if ((int )*mem_17 != (int )delim) {
      __CrestBranch(85, 43, 1);
      {
#line 114
      mem_18 = src + *i;
      {
      __CrestLoad(89, (unsigned long )mem_18, (long long )*mem_18);
      __CrestLoad(88, (unsigned long )0, (long long )0);
      __CrestApply2(87, 13, (long long )((int )*mem_18 != 0));
#line 114
      if ((int )*mem_18 != 0) {
        __CrestBranch(90, 46, 1);

      } else {
        __CrestBranch(91, 47, 0);
#line 114
        goto while_break;
      }
      }
      }
    } else {
      __CrestBranch(86, 48, 0);
#line 114
      goto while_break;
    }
    }
    }
    {
#line 116
    mem_19 = src + (*i - 1);
    {
    __CrestLoad(94, (unsigned long )mem_19, (long long )*mem_19);
    __CrestLoad(93, (unsigned long )0, (long long )64);
    __CrestApply2(92, 12, (long long )((int )*mem_19 == 64));
#line 116
    if ((int )*mem_19 == 64) {
      __CrestBranch(95, 52, 1);
#line 117
      escjunk = esc(src, i);
      __CrestHandleReturn(98, (long long )escjunk);
      __CrestStore(97, (unsigned long )(& escjunk));
      __CrestLoad(99, (unsigned long )(& escjunk), (long long )escjunk);
      __CrestLoad(100, (unsigned long )(& maxset), (long long )maxset);
#line 118
      tmp = addstr(escjunk, dest, j, maxset);
      __CrestHandleReturn(102, (long long )tmp);
      __CrestStore(101, (unsigned long )(& tmp));
      __CrestLoad(103, (unsigned long )(& tmp), (long long )tmp);
      __CrestStore(104, (unsigned long )(& junk));
#line 118
      junk = (bool )tmp;
    } else {
      __CrestBranch(96, 53, 0);
      {
#line 120
      mem_20 = src + *i;
      {
      __CrestLoad(107, (unsigned long )mem_20, (long long )*mem_20);
      __CrestLoad(106, (unsigned long )0, (long long )45);
      __CrestApply2(105, 13, (long long )((int )*mem_20 != 45));
#line 120
      if ((int )*mem_20 != 45) {
        __CrestBranch(108, 56, 1);
#line 121
        mem_21 = src + *i;
        __CrestLoad(110, (unsigned long )mem_21, (long long )*mem_21);
        __CrestLoad(111, (unsigned long )(& maxset), (long long )maxset);
#line 121
        tmp___0 = addstr(*mem_21, dest, j, maxset);
        __CrestHandleReturn(113, (long long )tmp___0);
        __CrestStore(112, (unsigned long )(& tmp___0));
        __CrestLoad(114, (unsigned long )(& tmp___0), (long long )tmp___0);
        __CrestStore(115, (unsigned long )(& junk));
#line 121
        junk = (bool )tmp___0;
      } else {
        __CrestBranch(109, 57, 0);
        {
        __CrestLoad(118, (unsigned long )j, (long long )*j);
        __CrestLoad(117, (unsigned long )0, (long long )1);
        __CrestApply2(116, 15, (long long )(*j <= 1));
#line 122
        if (*j <= 1) {
          __CrestBranch(119, 58, 1);
          __CrestLoad(121, (unsigned long )0, (long long )((char )'-'));
          __CrestLoad(122, (unsigned long )(& maxset), (long long )maxset);
#line 123
          tmp___1 = addstr((char )'-', dest, j, maxset);
          __CrestHandleReturn(124, (long long )tmp___1);
          __CrestStore(123, (unsigned long )(& tmp___1));
          __CrestLoad(125, (unsigned long )(& tmp___1), (long long )tmp___1);
          __CrestStore(126, (unsigned long )(& junk));
#line 123
          junk = (bool )tmp___1;
        } else {
          __CrestBranch(120, 59, 0);
          {
#line 122
          mem_22 = src + (*i + 1);
          {
          __CrestLoad(129, (unsigned long )mem_22, (long long )*mem_22);
          __CrestLoad(128, (unsigned long )0, (long long )0);
          __CrestApply2(127, 12, (long long )((int )*mem_22 == 0));
#line 122
          if ((int )*mem_22 == 0) {
            __CrestBranch(130, 62, 1);
            __CrestLoad(132, (unsigned long )0, (long long )((char )'-'));
            __CrestLoad(133, (unsigned long )(& maxset), (long long )maxset);
#line 123
            tmp___1 = addstr((char )'-', dest, j, maxset);
            __CrestHandleReturn(135, (long long )tmp___1);
            __CrestStore(134, (unsigned long )(& tmp___1));
            __CrestLoad(136, (unsigned long )(& tmp___1), (long long )tmp___1);
            __CrestStore(137, (unsigned long )(& junk));
#line 123
            junk = (bool )tmp___1;
          } else {
            __CrestBranch(131, 63, 0);
#line 124
            tmp___4 = __ctype_b_loc();
            __CrestClearStack(138);
            {
#line 124
            mem_23 = src + (*i - 1);
#line 124
            mem_24 = *tmp___4 + (int )*mem_23;
            {
            __CrestLoad(143, (unsigned long )mem_24, (long long )*mem_24);
            __CrestLoad(142, (unsigned long )0, (long long )8);
            __CrestApply2(141, 5, (long long )((int const   )*mem_24 & 8));
            __CrestLoad(140, (unsigned long )0, (long long )0);
            __CrestApply2(139, 13, (long long )(((int const   )*mem_24 & 8) != 0));
#line 124
            if (((int const   )*mem_24 & 8) != 0) {
              __CrestBranch(144, 67, 1);
#line 124
              tmp___5 = __ctype_b_loc();
              __CrestClearStack(146);
              {
#line 124
              mem_25 = src + (*i + 1);
#line 124
              mem_26 = *tmp___5 + (int )*mem_25;
              {
              __CrestLoad(151, (unsigned long )mem_26, (long long )*mem_26);
              __CrestLoad(150, (unsigned long )0, (long long )8);
              __CrestApply2(149, 5, (long long )((int const   )*mem_26 & 8));
              __CrestLoad(148, (unsigned long )0, (long long )0);
              __CrestApply2(147, 13, (long long )(((int const   )*mem_26 & 8) != 0));
#line 124
              if (((int const   )*mem_26 & 8) != 0) {
                __CrestBranch(152, 71, 1);
                {
#line 124
                mem_27 = src + (*i - 1);
#line 124
                mem_28 = src + (*i + 1);
                {
                __CrestLoad(156, (unsigned long )mem_27, (long long )*mem_27);
                __CrestLoad(155, (unsigned long )mem_28, (long long )*mem_28);
                __CrestApply2(154, 15, (long long )((int )*mem_27 <= (int )*mem_28));
#line 124
                if ((int )*mem_27 <= (int )*mem_28) {
                  __CrestBranch(157, 74, 1);
#line 127
                  mem_29 = src + (*i - 1);
                  __CrestLoad(161, (unsigned long )mem_29, (long long )*mem_29);
                  __CrestLoad(160, (unsigned long )0, (long long )1);
                  __CrestApply2(159, 0, (long long )((int )*mem_29 + 1));
                  __CrestStore(162, (unsigned long )(& k));
#line 127
                  k = (int )*mem_29 + 1;
                  {
#line 127
                  while (1) {
                    while_continue___0: /* CIL Label */ ;
                    {
#line 127
                    mem_30 = src + (*i + 1);
                    {
                    __CrestLoad(165, (unsigned long )(& k), (long long )k);
                    __CrestLoad(164, (unsigned long )mem_30, (long long )*mem_30);
                    __CrestApply2(163, 15, (long long )(k <= (int )*mem_30));
#line 127
                    if (k <= (int )*mem_30) {
                      __CrestBranch(166, 81, 1);

                    } else {
                      __CrestBranch(167, 82, 0);
#line 127
                      goto while_break___0;
                    }
                    }
                    }
                    __CrestLoad(168, (unsigned long )(& k), (long long )k);
                    __CrestLoad(169, (unsigned long )(& maxset), (long long )maxset);
#line 129
                    tmp___2 = addstr((char )k, dest, j, maxset);
                    __CrestHandleReturn(171, (long long )tmp___2);
                    __CrestStore(170, (unsigned long )(& tmp___2));
                    __CrestLoad(172, (unsigned long )(& tmp___2), (long long )tmp___2);
                    __CrestStore(173, (unsigned long )(& junk));
#line 129
                    junk = (bool )tmp___2;
                    __CrestLoad(176, (unsigned long )(& k), (long long )k);
                    __CrestLoad(175, (unsigned long )0, (long long )1);
                    __CrestApply2(174, 0, (long long )(k + 1));
                    __CrestStore(177, (unsigned long )(& k));
#line 127
                    k ++;
                  }
                  while_break___0: /* CIL Label */ ;
                  }
                  __CrestLoad(180, (unsigned long )i, (long long )*i);
                  __CrestLoad(179, (unsigned long )0, (long long )1);
                  __CrestApply2(178, 0, (long long )(*i + 1));
                  __CrestStore(181, (unsigned long )i);
#line 131
                  (*i) ++;
                } else {
                  __CrestBranch(158, 86, 0);
                  __CrestLoad(182, (unsigned long )0, (long long )((char )'-'));
                  __CrestLoad(183, (unsigned long )(& maxset), (long long )maxset);
#line 134
                  tmp___3 = addstr((char )'-', dest, j, maxset);
                  __CrestHandleReturn(185, (long long )tmp___3);
                  __CrestStore(184, (unsigned long )(& tmp___3));
                  __CrestLoad(186, (unsigned long )(& tmp___3), (long long )tmp___3);
                  __CrestStore(187, (unsigned long )(& junk));
#line 134
                  junk = (bool )tmp___3;
                }
                }
                }
              } else {
                __CrestBranch(153, 87, 0);
                __CrestLoad(188, (unsigned long )0, (long long )((char )'-'));
                __CrestLoad(189, (unsigned long )(& maxset), (long long )maxset);
#line 134
                tmp___3 = addstr((char )'-', dest, j, maxset);
                __CrestHandleReturn(191, (long long )tmp___3);
                __CrestStore(190, (unsigned long )(& tmp___3));
                __CrestLoad(192, (unsigned long )(& tmp___3), (long long )tmp___3);
                __CrestStore(193, (unsigned long )(& junk));
#line 134
                junk = (bool )tmp___3;
              }
              }
              }
            } else {
              __CrestBranch(145, 88, 0);
              __CrestLoad(194, (unsigned long )0, (long long )((char )'-'));
              __CrestLoad(195, (unsigned long )(& maxset), (long long )maxset);
#line 134
              tmp___3 = addstr((char )'-', dest, j, maxset);
              __CrestHandleReturn(197, (long long )tmp___3);
              __CrestStore(196, (unsigned long )(& tmp___3));
              __CrestLoad(198, (unsigned long )(& tmp___3), (long long )tmp___3);
              __CrestStore(199, (unsigned long )(& junk));
#line 134
              junk = (bool )tmp___3;
            }
            }
            }
          }
          }
          }
        }
        }
      }
      }
      }
    }
    }
    }
    __CrestLoad(202, (unsigned long )i, (long long )*i);
    __CrestLoad(201, (unsigned long )0, (long long )1);
    __CrestApply2(200, 0, (long long )(*i + 1));
    __CrestStore(203, (unsigned long )i);
#line 135
    (*i) ++;
  }
  while_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(204);
#line 101
  return;
  }
}
}
#line 139 "replace.c"
bool getccl(char *arg , int *i , char *pat , int *j ) 
{ 
  int jstart ;
  bool junk ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  char *mem_10 ;
  char *mem_11 ;
  char *mem_12 ;
  bool __retres13 ;

  {
  __CrestCall(205, 5);

  __CrestLoad(208, (unsigned long )i, (long long )*i);
  __CrestLoad(207, (unsigned long )0, (long long )1);
  __CrestApply2(206, 0, (long long )(*i + 1));
  __CrestStore(209, (unsigned long )i);
#line 149
  (*i) ++;
  {
#line 150
  mem_10 = arg + *i;
  {
  __CrestLoad(212, (unsigned long )mem_10, (long long )*mem_10);
  __CrestLoad(211, (unsigned long )0, (long long )94);
  __CrestApply2(210, 12, (long long )((int )*mem_10 == 94));
#line 150
  if ((int )*mem_10 == 94) {
    __CrestBranch(213, 97, 1);
    __CrestLoad(215, (unsigned long )0, (long long )((char )'!'));
    __CrestLoad(216, (unsigned long )0, (long long )100);
#line 151
    tmp = addstr((char )'!', pat, j, 100);
    __CrestHandleReturn(218, (long long )tmp);
    __CrestStore(217, (unsigned long )(& tmp));
    __CrestLoad(219, (unsigned long )(& tmp), (long long )tmp);
    __CrestStore(220, (unsigned long )(& junk));
#line 151
    junk = (bool )tmp;
    __CrestLoad(223, (unsigned long )i, (long long )*i);
    __CrestLoad(222, (unsigned long )0, (long long )1);
    __CrestApply2(221, 0, (long long )(*i + 1));
    __CrestStore(224, (unsigned long )i);
#line 152
    (*i) ++;
  } else {
    __CrestBranch(214, 98, 0);
    __CrestLoad(225, (unsigned long )0, (long long )((char )'['));
    __CrestLoad(226, (unsigned long )0, (long long )100);
#line 154
    tmp___0 = addstr((char )'[', pat, j, 100);
    __CrestHandleReturn(228, (long long )tmp___0);
    __CrestStore(227, (unsigned long )(& tmp___0));
    __CrestLoad(229, (unsigned long )(& tmp___0), (long long )tmp___0);
    __CrestStore(230, (unsigned long )(& junk));
#line 154
    junk = (bool )tmp___0;
  }
  }
  }
  __CrestLoad(231, (unsigned long )j, (long long )*j);
  __CrestStore(232, (unsigned long )(& jstart));
#line 155
  jstart = *j;
  __CrestLoad(233, (unsigned long )0, (long long )(char)0);
  __CrestLoad(234, (unsigned long )0, (long long )100);
#line 156
  tmp___1 = addstr((char)0, pat, j, 100);
  __CrestHandleReturn(236, (long long )tmp___1);
  __CrestStore(235, (unsigned long )(& tmp___1));
  __CrestLoad(237, (unsigned long )(& tmp___1), (long long )tmp___1);
  __CrestStore(238, (unsigned long )(& junk));
#line 156
  junk = (bool )tmp___1;
  __CrestLoad(239, (unsigned long )0, (long long )((char )']'));
  __CrestLoad(240, (unsigned long )0, (long long )100);
#line 157
  dodash((char )']', arg, i, pat, j, 100);
  __CrestClearStack(241);
#line 158
  mem_11 = pat + jstart;
  __CrestLoad(246, (unsigned long )j, (long long )*j);
  __CrestLoad(245, (unsigned long )(& jstart), (long long )jstart);
  __CrestApply2(244, 1, (long long )(*j - jstart));
  __CrestLoad(243, (unsigned long )0, (long long )1);
  __CrestApply2(242, 1, (long long )((*j - jstart) - 1));
  __CrestStore(247, (unsigned long )mem_11);
#line 158
  *mem_11 = (char )((*j - jstart) - 1);
  {
#line 159
  mem_12 = arg + *i;
  __CrestLoad(250, (unsigned long )mem_12, (long long )*mem_12);
  __CrestLoad(249, (unsigned long )0, (long long )93);
  __CrestApply2(248, 12, (long long )((int )*mem_12 == 93));
  __CrestStore(251, (unsigned long )(& __retres13));
#line 159
  __retres13 = (bool )((int )*mem_12 == 93);
#line 159
  goto return_label;
  }
  return_label: /* CIL Label */ 
  {
  __CrestLoad(252, (unsigned long )(& __retres13), (long long )__retres13);
  __CrestReturn(253);
#line 139
  return (__retres13);
  }
}
}
#line 162 "replace.c"
void stclose(char *pat , int *j , int lastj ) 
{ 
  int jt ;
  int jp ;
  bool junk ;
  int tmp ;
  char *mem_8 ;
  char *mem_9 ;

  {
  __CrestCall(255, 6);
  __CrestStore(254, (unsigned long )(& lastj));
  __CrestLoad(258, (unsigned long )j, (long long )*j);
  __CrestLoad(257, (unsigned long )0, (long long )1);
  __CrestApply2(256, 1, (long long )(*j - 1));
  __CrestStore(259, (unsigned long )(& jp));
#line 173
  jp = *j - 1;
  {
#line 173
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(262, (unsigned long )(& jp), (long long )jp);
    __CrestLoad(261, (unsigned long )(& lastj), (long long )lastj);
    __CrestApply2(260, 17, (long long )(jp >= lastj));
#line 173
    if (jp >= lastj) {
      __CrestBranch(263, 110, 1);

    } else {
      __CrestBranch(264, 111, 0);
#line 173
      goto while_break;
    }
    }
    __CrestLoad(267, (unsigned long )(& jp), (long long )jp);
    __CrestLoad(266, (unsigned long )0, (long long )1);
    __CrestApply2(265, 0, (long long )(jp + 1));
    __CrestStore(268, (unsigned long )(& jt));
#line 175
    jt = jp + 1;
#line 176
    mem_8 = pat + jp;
    __CrestLoad(269, (unsigned long )mem_8, (long long )*mem_8);
    __CrestLoad(270, (unsigned long )0, (long long )100);
#line 176
    tmp = addstr(*mem_8, pat, & jt, 100);
    __CrestHandleReturn(272, (long long )tmp);
    __CrestStore(271, (unsigned long )(& tmp));
    __CrestLoad(273, (unsigned long )(& tmp), (long long )tmp);
    __CrestStore(274, (unsigned long )(& junk));
#line 176
    junk = (bool )tmp;
    __CrestLoad(277, (unsigned long )(& jp), (long long )jp);
    __CrestLoad(276, (unsigned long )0, (long long )1);
    __CrestApply2(275, 1, (long long )(jp - 1));
    __CrestStore(278, (unsigned long )(& jp));
#line 173
    jp --;
  }
  while_break: /* CIL Label */ ;
  }
  __CrestLoad(281, (unsigned long )j, (long long )*j);
  __CrestLoad(280, (unsigned long )0, (long long )1);
  __CrestApply2(279, 0, (long long )(*j + 1));
  __CrestStore(282, (unsigned long )j);
#line 178
  (*j) ++;
#line 179
  mem_9 = pat + lastj;
  __CrestLoad(283, (unsigned long )0, (long long )((char )'*'));
  __CrestStore(284, (unsigned long )mem_9);
#line 179
  *mem_9 = (char )'*';

  {
  __CrestReturn(285);
#line 162
  return;
  }
}
}
#line 182 "replace.c"
bool in_set_2(char c ) 
{ 
  int tmp ;
  bool __retres3 ;

  {
  __CrestCall(287, 7);
  __CrestStore(286, (unsigned long )(& c));
  {
  __CrestLoad(290, (unsigned long )(& c), (long long )c);
  __CrestLoad(289, (unsigned long )0, (long long )37);
  __CrestApply2(288, 12, (long long )((int )c == 37));
#line 185
  if ((int )c == 37) {
    __CrestBranch(291, 118, 1);
    __CrestLoad(293, (unsigned long )0, (long long )1);
    __CrestStore(294, (unsigned long )(& tmp));
#line 185
    tmp = 1;
  } else {
    __CrestBranch(292, 119, 0);
    {
    __CrestLoad(297, (unsigned long )(& c), (long long )c);
    __CrestLoad(296, (unsigned long )0, (long long )36);
    __CrestApply2(295, 12, (long long )((int )c == 36));
#line 185
    if ((int )c == 36) {
      __CrestBranch(298, 120, 1);
      __CrestLoad(300, (unsigned long )0, (long long )1);
      __CrestStore(301, (unsigned long )(& tmp));
#line 185
      tmp = 1;
    } else {
      __CrestBranch(299, 121, 0);
      {
      __CrestLoad(304, (unsigned long )(& c), (long long )c);
      __CrestLoad(303, (unsigned long )0, (long long )42);
      __CrestApply2(302, 12, (long long )((int )c == 42));
#line 185
      if ((int )c == 42) {
        __CrestBranch(305, 122, 1);
        __CrestLoad(307, (unsigned long )0, (long long )1);
        __CrestStore(308, (unsigned long )(& tmp));
#line 185
        tmp = 1;
      } else {
        __CrestBranch(306, 123, 0);
        __CrestLoad(309, (unsigned long )0, (long long )0);
        __CrestStore(310, (unsigned long )(& tmp));
#line 185
        tmp = 0;
      }
      }
    }
    }
  }
  }
  __CrestLoad(311, (unsigned long )(& tmp), (long long )tmp);
  __CrestStore(312, (unsigned long )(& __retres3));
#line 185
  __retres3 = (bool )tmp;
  {
  __CrestLoad(313, (unsigned long )(& __retres3), (long long )__retres3);
  __CrestReturn(314);
#line 182
  return (__retres3);
  }
}
}
#line 188 "replace.c"
bool in_pat_set(char c ) 
{ 
  int tmp ;
  bool __retres3 ;

  {
  __CrestCall(316, 8);
  __CrestStore(315, (unsigned long )(& c));
  {
  __CrestLoad(319, (unsigned long )(& c), (long long )c);
  __CrestLoad(318, (unsigned long )0, (long long )99);
  __CrestApply2(317, 12, (long long )((int )c == 99));
#line 191
  if ((int )c == 99) {
    __CrestBranch(320, 127, 1);
    __CrestLoad(322, (unsigned long )0, (long long )1);
    __CrestStore(323, (unsigned long )(& tmp));
#line 191
    tmp = 1;
  } else {
    __CrestBranch(321, 128, 0);
    {
    __CrestLoad(326, (unsigned long )(& c), (long long )c);
    __CrestLoad(325, (unsigned long )0, (long long )37);
    __CrestApply2(324, 12, (long long )((int )c == 37));
#line 191
    if ((int )c == 37) {
      __CrestBranch(327, 129, 1);
      __CrestLoad(329, (unsigned long )0, (long long )1);
      __CrestStore(330, (unsigned long )(& tmp));
#line 191
      tmp = 1;
    } else {
      __CrestBranch(328, 130, 0);
      {
      __CrestLoad(333, (unsigned long )(& c), (long long )c);
      __CrestLoad(332, (unsigned long )0, (long long )36);
      __CrestApply2(331, 12, (long long )((int )c == 36));
#line 191
      if ((int )c == 36) {
        __CrestBranch(334, 131, 1);
        __CrestLoad(336, (unsigned long )0, (long long )1);
        __CrestStore(337, (unsigned long )(& tmp));
#line 191
        tmp = 1;
      } else {
        __CrestBranch(335, 132, 0);
        {
        __CrestLoad(340, (unsigned long )(& c), (long long )c);
        __CrestLoad(339, (unsigned long )0, (long long )63);
        __CrestApply2(338, 12, (long long )((int )c == 63));
#line 191
        if ((int )c == 63) {
          __CrestBranch(341, 133, 1);
          __CrestLoad(343, (unsigned long )0, (long long )1);
          __CrestStore(344, (unsigned long )(& tmp));
#line 191
          tmp = 1;
        } else {
          __CrestBranch(342, 134, 0);
          {
          __CrestLoad(347, (unsigned long )(& c), (long long )c);
          __CrestLoad(346, (unsigned long )0, (long long )91);
          __CrestApply2(345, 12, (long long )((int )c == 91));
#line 191
          if ((int )c == 91) {
            __CrestBranch(348, 135, 1);
            __CrestLoad(350, (unsigned long )0, (long long )1);
            __CrestStore(351, (unsigned long )(& tmp));
#line 191
            tmp = 1;
          } else {
            __CrestBranch(349, 136, 0);
            {
            __CrestLoad(354, (unsigned long )(& c), (long long )c);
            __CrestLoad(353, (unsigned long )0, (long long )33);
            __CrestApply2(352, 12, (long long )((int )c == 33));
#line 191
            if ((int )c == 33) {
              __CrestBranch(355, 137, 1);
              __CrestLoad(357, (unsigned long )0, (long long )1);
              __CrestStore(358, (unsigned long )(& tmp));
#line 191
              tmp = 1;
            } else {
              __CrestBranch(356, 138, 0);
              {
              __CrestLoad(361, (unsigned long )(& c), (long long )c);
              __CrestLoad(360, (unsigned long )0, (long long )42);
              __CrestApply2(359, 12, (long long )((int )c == 42));
#line 191
              if ((int )c == 42) {
                __CrestBranch(362, 139, 1);
                __CrestLoad(364, (unsigned long )0, (long long )1);
                __CrestStore(365, (unsigned long )(& tmp));
#line 191
                tmp = 1;
              } else {
                __CrestBranch(363, 140, 0);
                __CrestLoad(366, (unsigned long )0, (long long )0);
                __CrestStore(367, (unsigned long )(& tmp));
#line 191
                tmp = 0;
              }
              }
            }
            }
          }
          }
        }
        }
      }
      }
    }
    }
  }
  }
  __CrestLoad(368, (unsigned long )(& tmp), (long long )tmp);
  __CrestStore(369, (unsigned long )(& __retres3));
#line 191
  __retres3 = (bool )tmp;
  {
  __CrestLoad(370, (unsigned long )(& __retres3), (long long )__retres3);
  __CrestReturn(371);
#line 188
  return (__retres3);
  }
}
}
#line 195 "replace.c"
int makepat(char *arg , int start , char delim , char *pat ) 
{ 
  int result ;
  int i ;
  int j ;
  int lastj ;
  int lj ;
  bool done ;
  bool junk ;
  bool getres ;
  char escjunk ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  bool tmp___2 ;
  int tmp___3 ;
  int tmp___4 ;
  int tmp___5 ;
  char *mem_21 ;
  char *mem_22 ;
  char *mem_23 ;
  char *mem_24 ;
  char *mem_25 ;
  char *mem_26 ;
  char *mem_27 ;
  char *mem_28 ;
  char *mem_29 ;
  char *mem_30 ;

  {
  __CrestCall(374, 9);
  __CrestStore(373, (unsigned long )(& delim));
  __CrestStore(372, (unsigned long )(& start));
  __CrestLoad(375, (unsigned long )0, (long long )0);
  __CrestStore(376, (unsigned long )(& j));
#line 208
  j = 0;
  __CrestLoad(377, (unsigned long )(& start), (long long )start);
  __CrestStore(378, (unsigned long )(& i));
#line 209
  i = start;
  __CrestLoad(379, (unsigned long )0, (long long )0);
  __CrestStore(380, (unsigned long )(& lastj));
#line 210
  lastj = 0;
  __CrestLoad(381, (unsigned long )0, (long long )((bool )0));
  __CrestStore(382, (unsigned long )(& done));
#line 211
  done = (bool )0;
  {
#line 212
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(385, (unsigned long )(& done), (long long )done);
    __CrestLoad(384, (unsigned long )0, (long long )0);
    __CrestApply2(383, 12, (long long )(done == 0));
#line 212
    if (done == 0) {
      __CrestBranch(386, 148, 1);
      {
#line 212
      mem_21 = arg + i;
      {
      __CrestLoad(390, (unsigned long )mem_21, (long long )*mem_21);
      __CrestLoad(389, (unsigned long )(& delim), (long long )delim);
      __CrestApply2(388, 13, (long long )((int )*mem_21 != (int )delim));
#line 212
      if ((int )*mem_21 != (int )delim) {
        __CrestBranch(391, 151, 1);
        {
#line 212
        mem_22 = arg + i;
        {
        __CrestLoad(395, (unsigned long )mem_22, (long long )*mem_22);
        __CrestLoad(394, (unsigned long )0, (long long )0);
        __CrestApply2(393, 13, (long long )((int )*mem_22 != 0));
#line 212
        if ((int )*mem_22 != 0) {
          __CrestBranch(396, 154, 1);

        } else {
          __CrestBranch(397, 155, 0);
#line 212
          goto while_break;
        }
        }
        }
      } else {
        __CrestBranch(392, 156, 0);
#line 212
        goto while_break;
      }
      }
      }
    } else {
      __CrestBranch(387, 157, 0);
#line 212
      goto while_break;
    }
    }
    __CrestLoad(398, (unsigned long )(& j), (long long )j);
    __CrestStore(399, (unsigned long )(& lj));
#line 213
    lj = j;
    {
#line 214
    mem_23 = arg + i;
    {
    __CrestLoad(402, (unsigned long )mem_23, (long long )*mem_23);
    __CrestLoad(401, (unsigned long )0, (long long )63);
    __CrestApply2(400, 12, (long long )((int )*mem_23 == 63));
#line 214
    if ((int )*mem_23 == 63) {
      __CrestBranch(403, 162, 1);
      __CrestLoad(405, (unsigned long )0, (long long )((char )'?'));
      __CrestLoad(406, (unsigned long )0, (long long )100);
#line 215
      tmp = addstr((char )'?', pat, & j, 100);
      __CrestHandleReturn(408, (long long )tmp);
      __CrestStore(407, (unsigned long )(& tmp));
      __CrestLoad(409, (unsigned long )(& tmp), (long long )tmp);
      __CrestStore(410, (unsigned long )(& junk));
#line 215
      junk = (bool )tmp;
    } else {
      __CrestBranch(404, 163, 0);
      {
#line 216
      mem_24 = arg + i;
      {
      __CrestLoad(413, (unsigned long )mem_24, (long long )*mem_24);
      __CrestLoad(412, (unsigned long )0, (long long )37);
      __CrestApply2(411, 12, (long long )((int )*mem_24 == 37));
#line 216
      if ((int )*mem_24 == 37) {
        __CrestBranch(414, 166, 1);
        {
        __CrestLoad(418, (unsigned long )(& i), (long long )i);
        __CrestLoad(417, (unsigned long )(& start), (long long )start);
        __CrestApply2(416, 12, (long long )(i == start));
#line 216
        if (i == start) {
          __CrestBranch(419, 167, 1);
          __CrestLoad(421, (unsigned long )0, (long long )((char )'%'));
          __CrestLoad(422, (unsigned long )0, (long long )100);
#line 217
          tmp___0 = addstr((char )'%', pat, & j, 100);
          __CrestHandleReturn(424, (long long )tmp___0);
          __CrestStore(423, (unsigned long )(& tmp___0));
          __CrestLoad(425, (unsigned long )(& tmp___0), (long long )tmp___0);
          __CrestStore(426, (unsigned long )(& junk));
#line 217
          junk = (bool )tmp___0;
        } else {
          __CrestBranch(420, 168, 0);
#line 216
          goto _L___0;
        }
        }
      } else {
        __CrestBranch(415, 169, 0);
        _L___0: /* CIL Label */ 
        {
#line 218
        mem_25 = arg + i;
        {
        __CrestLoad(429, (unsigned long )mem_25, (long long )*mem_25);
        __CrestLoad(428, (unsigned long )0, (long long )36);
        __CrestApply2(427, 12, (long long )((int )*mem_25 == 36));
#line 218
        if ((int )*mem_25 == 36) {
          __CrestBranch(430, 172, 1);
          {
#line 218
          mem_26 = arg + (i + 1);
          {
          __CrestLoad(434, (unsigned long )mem_26, (long long )*mem_26);
          __CrestLoad(433, (unsigned long )(& delim), (long long )delim);
          __CrestApply2(432, 12, (long long )((int )*mem_26 == (int )delim));
#line 218
          if ((int )*mem_26 == (int )delim) {
            __CrestBranch(435, 175, 1);
            __CrestLoad(437, (unsigned long )0, (long long )((char )'$'));
            __CrestLoad(438, (unsigned long )0, (long long )100);
#line 219
            tmp___1 = addstr((char )'$', pat, & j, 100);
            __CrestHandleReturn(440, (long long )tmp___1);
            __CrestStore(439, (unsigned long )(& tmp___1));
            __CrestLoad(441, (unsigned long )(& tmp___1), (long long )tmp___1);
            __CrestStore(442, (unsigned long )(& junk));
#line 219
            junk = (bool )tmp___1;
          } else {
            __CrestBranch(436, 176, 0);
#line 218
            goto _L;
          }
          }
          }
        } else {
          __CrestBranch(431, 177, 0);
          _L: /* CIL Label */ 
          {
#line 220
          mem_27 = arg + i;
          {
          __CrestLoad(445, (unsigned long )mem_27, (long long )*mem_27);
          __CrestLoad(444, (unsigned long )0, (long long )91);
          __CrestApply2(443, 12, (long long )((int )*mem_27 == 91));
#line 220
          if ((int )*mem_27 == 91) {
            __CrestBranch(446, 180, 1);
#line 222
            getres = getccl(arg, & i, pat, & j);
            __CrestHandleReturn(449, (long long )getres);
            __CrestStore(448, (unsigned long )(& getres));
            __CrestLoad(452, (unsigned long )(& getres), (long long )getres);
            __CrestLoad(451, (unsigned long )0, (long long )0);
            __CrestApply2(450, 12, (long long )((int )getres == 0));
            __CrestStore(453, (unsigned long )(& done));
#line 223
            done = (bool )((int )getres == 0);
          } else {
            __CrestBranch(447, 181, 0);
            {
#line 225
            mem_28 = arg + i;
            {
            __CrestLoad(456, (unsigned long )mem_28, (long long )*mem_28);
            __CrestLoad(455, (unsigned long )0, (long long )42);
            __CrestApply2(454, 12, (long long )((int )*mem_28 == 42));
#line 225
            if ((int )*mem_28 == 42) {
              __CrestBranch(457, 184, 1);
              {
              __CrestLoad(461, (unsigned long )(& i), (long long )i);
              __CrestLoad(460, (unsigned long )(& start), (long long )start);
              __CrestApply2(459, 14, (long long )(i > start));
#line 225
              if (i > start) {
                __CrestBranch(462, 185, 1);
                __CrestLoad(464, (unsigned long )(& lastj), (long long )lastj);
                __CrestStore(465, (unsigned long )(& lj));
#line 227
                lj = lastj;
#line 228
                mem_29 = pat + lj;
                __CrestLoad(466, (unsigned long )mem_29, (long long )*mem_29);
#line 228
                tmp___2 = in_set_2(*mem_29);
                __CrestHandleReturn(468, (long long )tmp___2);
                __CrestStore(467, (unsigned long )(& tmp___2));
                {
                __CrestLoad(471, (unsigned long )(& tmp___2), (long long )tmp___2);
                __CrestLoad(470, (unsigned long )0, (long long )0);
                __CrestApply2(469, 13, (long long )(tmp___2 != 0));
#line 228
                if (tmp___2 != 0) {
                  __CrestBranch(472, 187, 1);
                  __CrestLoad(474, (unsigned long )0, (long long )((bool )1));
                  __CrestStore(475, (unsigned long )(& done));
#line 229
                  done = (bool )1;
                } else {
                  __CrestBranch(473, 188, 0);
                  __CrestLoad(476, (unsigned long )(& lastj), (long long )lastj);
#line 231
                  stclose(pat, & j, lastj);
                  __CrestClearStack(477);
                }
                }
              } else {
                __CrestBranch(463, 189, 0);
                __CrestLoad(478, (unsigned long )0, (long long )((char )'c'));
                __CrestLoad(479, (unsigned long )0, (long long )100);
#line 235
                tmp___3 = addstr((char )'c', pat, & j, 100);
                __CrestHandleReturn(481, (long long )tmp___3);
                __CrestStore(480, (unsigned long )(& tmp___3));
                __CrestLoad(482, (unsigned long )(& tmp___3), (long long )tmp___3);
                __CrestStore(483, (unsigned long )(& junk));
#line 235
                junk = (bool )tmp___3;
#line 236
                escjunk = esc(arg, & i);
                __CrestHandleReturn(485, (long long )escjunk);
                __CrestStore(484, (unsigned long )(& escjunk));
                __CrestLoad(486, (unsigned long )(& escjunk), (long long )escjunk);
                __CrestLoad(487, (unsigned long )0, (long long )100);
#line 237
                tmp___4 = addstr(escjunk, pat, & j, 100);
                __CrestHandleReturn(489, (long long )tmp___4);
                __CrestStore(488, (unsigned long )(& tmp___4));
                __CrestLoad(490, (unsigned long )(& tmp___4), (long long )tmp___4);
                __CrestStore(491, (unsigned long )(& junk));
#line 237
                junk = (bool )tmp___4;
              }
              }
            } else {
              __CrestBranch(458, 190, 0);
              __CrestLoad(492, (unsigned long )0, (long long )((char )'c'));
              __CrestLoad(493, (unsigned long )0, (long long )100);
#line 235
              tmp___3 = addstr((char )'c', pat, & j, 100);
              __CrestHandleReturn(495, (long long )tmp___3);
              __CrestStore(494, (unsigned long )(& tmp___3));
              __CrestLoad(496, (unsigned long )(& tmp___3), (long long )tmp___3);
              __CrestStore(497, (unsigned long )(& junk));
#line 235
              junk = (bool )tmp___3;
#line 236
              escjunk = esc(arg, & i);
              __CrestHandleReturn(499, (long long )escjunk);
              __CrestStore(498, (unsigned long )(& escjunk));
              __CrestLoad(500, (unsigned long )(& escjunk), (long long )escjunk);
              __CrestLoad(501, (unsigned long )0, (long long )100);
#line 237
              tmp___4 = addstr(escjunk, pat, & j, 100);
              __CrestHandleReturn(503, (long long )tmp___4);
              __CrestStore(502, (unsigned long )(& tmp___4));
              __CrestLoad(504, (unsigned long )(& tmp___4), (long long )tmp___4);
              __CrestStore(505, (unsigned long )(& junk));
#line 237
              junk = (bool )tmp___4;
            }
            }
            }
          }
          }
          }
        }
        }
        }
      }
      }
      }
    }
    }
    }
    __CrestLoad(506, (unsigned long )(& lj), (long long )lj);
    __CrestStore(507, (unsigned long )(& lastj));
#line 239
    lastj = lj;
    {
    __CrestLoad(510, (unsigned long )(& done), (long long )done);
    __CrestLoad(509, (unsigned long )0, (long long )0);
    __CrestApply2(508, 12, (long long )(done == 0));
#line 240
    if (done == 0) {
      __CrestBranch(511, 193, 1);
      __CrestLoad(515, (unsigned long )(& i), (long long )i);
      __CrestLoad(514, (unsigned long )0, (long long )1);
      __CrestApply2(513, 0, (long long )(i + 1));
      __CrestStore(516, (unsigned long )(& i));
#line 241
      i ++;
    } else {
      __CrestBranch(512, 194, 0);

    }
    }
  }
  while_break: /* CIL Label */ ;
  }
  __CrestLoad(517, (unsigned long )0, (long long )((char )'\000'));
  __CrestLoad(518, (unsigned long )0, (long long )100);
#line 243
  tmp___5 = addstr((char )'\000', pat, & j, 100);
  __CrestHandleReturn(520, (long long )tmp___5);
  __CrestStore(519, (unsigned long )(& tmp___5));
  __CrestLoad(521, (unsigned long )(& tmp___5), (long long )tmp___5);
  __CrestStore(522, (unsigned long )(& junk));
#line 243
  junk = (bool )tmp___5;
  {
  __CrestLoad(525, (unsigned long )(& done), (long long )done);
  __CrestLoad(524, (unsigned long )0, (long long )0);
  __CrestApply2(523, 13, (long long )(done != 0));
#line 244
  if (done != 0) {
    __CrestBranch(526, 198, 1);
    __CrestLoad(528, (unsigned long )0, (long long )0);
    __CrestStore(529, (unsigned long )(& result));
#line 245
    result = 0;
  } else {
    __CrestBranch(527, 199, 0);
    {
#line 244
    mem_30 = arg + i;
    {
    __CrestLoad(532, (unsigned long )mem_30, (long long )*mem_30);
    __CrestLoad(531, (unsigned long )(& delim), (long long )delim);
    __CrestApply2(530, 13, (long long )((int )*mem_30 != (int )delim));
#line 244
    if ((int )*mem_30 != (int )delim) {
      __CrestBranch(533, 202, 1);
      __CrestLoad(535, (unsigned long )0, (long long )0);
      __CrestStore(536, (unsigned long )(& result));
#line 245
      result = 0;
    } else {
      __CrestBranch(534, 203, 0);
      {
      __CrestLoad(539, (unsigned long )(& junk), (long long )junk);
      __CrestLoad(538, (unsigned long )0, (long long )0);
      __CrestApply2(537, 12, (long long )(junk == 0));
#line 247
      if (junk == 0) {
        __CrestBranch(540, 204, 1);
        __CrestLoad(542, (unsigned long )0, (long long )0);
        __CrestStore(543, (unsigned long )(& result));
#line 248
        result = 0;
      } else {
        __CrestBranch(541, 205, 0);
        __CrestLoad(544, (unsigned long )(& i), (long long )i);
        __CrestStore(545, (unsigned long )(& result));
#line 250
        result = i;
      }
      }
    }
    }
    }
  }
  }
  {
  __CrestLoad(546, (unsigned long )(& result), (long long )result);
  __CrestReturn(547);
#line 251
  return (result);
  }
}
}
#line 254 "replace.c"
int getpat(char *arg , char *pat ) 
{ 
  int makeres ;
  int __retres4 ;

  {
  __CrestCall(548, 10);

  __CrestLoad(549, (unsigned long )0, (long long )0);
  __CrestLoad(550, (unsigned long )0, (long long )((char )'\000'));
#line 261
  makeres = makepat(arg, 0, (char )'\000', pat);
  __CrestHandleReturn(552, (long long )makeres);
  __CrestStore(551, (unsigned long )(& makeres));
  __CrestLoad(555, (unsigned long )(& makeres), (long long )makeres);
  __CrestLoad(554, (unsigned long )0, (long long )0);
  __CrestApply2(553, 14, (long long )(makeres > 0));
  __CrestStore(556, (unsigned long )(& __retres4));
#line 262
  __retres4 = makeres > 0;
  {
  __CrestLoad(557, (unsigned long )(& __retres4), (long long )__retres4);
  __CrestReturn(558);
#line 254
  return (__retres4);
  }
}
}
#line 265 "replace.c"
int makesub(char *arg , int from , character delim , char *sub ) 
{ 
  int result ;
  int i ;
  int j ;
  bool junk ;
  character escjunk ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  char *mem_13 ;
  char *mem_14 ;
  char *mem_15 ;
  char *mem_16 ;

  {
  __CrestCall(561, 11);
  __CrestStore(560, (unsigned long )(& delim));
  __CrestStore(559, (unsigned long )(& from));
  __CrestLoad(562, (unsigned long )0, (long long )0);
  __CrestStore(563, (unsigned long )(& j));
#line 277
  j = 0;
  __CrestLoad(564, (unsigned long )(& from), (long long )from);
  __CrestStore(565, (unsigned long )(& i));
#line 278
  i = from;
  {
#line 279
  while (1) {
    while_continue: /* CIL Label */ ;
    {
#line 279
    mem_13 = arg + i;
    {
    __CrestLoad(568, (unsigned long )mem_13, (long long )*mem_13);
    __CrestLoad(567, (unsigned long )(& delim), (long long )delim);
    __CrestApply2(566, 13, (long long )((int )*mem_13 != (int )delim));
#line 279
    if ((int )*mem_13 != (int )delim) {
      __CrestBranch(569, 217, 1);
      {
#line 279
      mem_14 = arg + i;
      {
      __CrestLoad(573, (unsigned long )mem_14, (long long )*mem_14);
      __CrestLoad(572, (unsigned long )0, (long long )0);
      __CrestApply2(571, 13, (long long )((int )*mem_14 != 0));
#line 279
      if ((int )*mem_14 != 0) {
        __CrestBranch(574, 220, 1);

      } else {
        __CrestBranch(575, 221, 0);
#line 279
        goto while_break;
      }
      }
      }
    } else {
      __CrestBranch(570, 222, 0);
#line 279
      goto while_break;
    }
    }
    }
    {
#line 280
    mem_15 = arg + i;
    {
    __CrestLoad(578, (unsigned long )mem_15, (long long )*mem_15);
    __CrestLoad(577, (unsigned long )0, (long long )38U);
    __CrestApply2(576, 12, (long long )((unsigned int )*mem_15 == 38U));
#line 280
    if ((unsigned int )*mem_15 == 38U) {
      __CrestBranch(579, 226, 1);
      __CrestLoad(581, (unsigned long )0, (long long )(char)-1);
      __CrestLoad(582, (unsigned long )0, (long long )100);
#line 281
      tmp = addstr((char)-1, sub, & j, 100);
      __CrestHandleReturn(584, (long long )tmp);
      __CrestStore(583, (unsigned long )(& tmp));
      __CrestLoad(585, (unsigned long )(& tmp), (long long )tmp);
      __CrestStore(586, (unsigned long )(& junk));
#line 281
      junk = (bool )tmp;
    } else {
      __CrestBranch(580, 227, 0);
#line 283
      escjunk = esc(arg, & i);
      __CrestHandleReturn(588, (long long )escjunk);
      __CrestStore(587, (unsigned long )(& escjunk));
      __CrestLoad(589, (unsigned long )(& escjunk), (long long )escjunk);
      __CrestLoad(590, (unsigned long )0, (long long )100);
#line 284
      tmp___0 = addstr(escjunk, sub, & j, 100);
      __CrestHandleReturn(592, (long long )tmp___0);
      __CrestStore(591, (unsigned long )(& tmp___0));
      __CrestLoad(593, (unsigned long )(& tmp___0), (long long )tmp___0);
      __CrestStore(594, (unsigned long )(& junk));
#line 284
      junk = (bool )tmp___0;
    }
    }
    }
    __CrestLoad(597, (unsigned long )(& i), (long long )i);
    __CrestLoad(596, (unsigned long )0, (long long )1);
    __CrestApply2(595, 0, (long long )(i + 1));
    __CrestStore(598, (unsigned long )(& i));
#line 286
    i ++;
  }
  while_break: /* CIL Label */ ;
  }
  {
#line 288
  mem_16 = arg + i;
  {
  __CrestLoad(601, (unsigned long )mem_16, (long long )*mem_16);
  __CrestLoad(600, (unsigned long )(& delim), (long long )delim);
  __CrestApply2(599, 13, (long long )((int )*mem_16 != (int )delim));
#line 288
  if ((int )*mem_16 != (int )delim) {
    __CrestBranch(602, 233, 1);
    __CrestLoad(604, (unsigned long )0, (long long )0);
    __CrestStore(605, (unsigned long )(& result));
#line 289
    result = 0;
  } else {
    __CrestBranch(603, 234, 0);
    __CrestLoad(606, (unsigned long )0, (long long )((char )'\000'));
    __CrestLoad(607, (unsigned long )0, (long long )100);
#line 291
    tmp___1 = addstr((char )'\000', sub, & j, 100);
    __CrestHandleReturn(609, (long long )tmp___1);
    __CrestStore(608, (unsigned long )(& tmp___1));
    __CrestLoad(610, (unsigned long )(& tmp___1), (long long )tmp___1);
    __CrestStore(611, (unsigned long )(& junk));
#line 291
    junk = (bool )tmp___1;
    {
    __CrestLoad(614, (unsigned long )(& junk), (long long )junk);
    __CrestLoad(613, (unsigned long )0, (long long )0);
    __CrestApply2(612, 12, (long long )(junk == 0));
#line 292
    if (junk == 0) {
      __CrestBranch(615, 236, 1);
      __CrestLoad(617, (unsigned long )0, (long long )0);
      __CrestStore(618, (unsigned long )(& result));
#line 293
      result = 0;
    } else {
      __CrestBranch(616, 237, 0);
      __CrestLoad(619, (unsigned long )(& i), (long long )i);
      __CrestStore(620, (unsigned long )(& result));
#line 295
      result = i;
    }
    }
  }
  }
  }
  {
  __CrestLoad(621, (unsigned long )(& result), (long long )result);
  __CrestReturn(622);
#line 297
  return (result);
  }
}
}
#line 300 "replace.c"
bool getsub(char *arg , char *sub ) 
{ 
  int makeres ;
  bool __retres4 ;

  {
  __CrestCall(623, 12);

  __CrestLoad(624, (unsigned long )0, (long long )0);
  __CrestLoad(625, (unsigned long )0, (long long )((character )'\000'));
#line 307
  makeres = makesub(arg, 0, (character )'\000', sub);
  __CrestHandleReturn(627, (long long )makeres);
  __CrestStore(626, (unsigned long )(& makeres));
  __CrestLoad(630, (unsigned long )(& makeres), (long long )makeres);
  __CrestLoad(629, (unsigned long )0, (long long )0);
  __CrestApply2(628, 14, (long long )(makeres > 0));
  __CrestStore(631, (unsigned long )(& __retres4));
#line 308
  __retres4 = (bool )(makeres > 0);
  {
  __CrestLoad(632, (unsigned long )(& __retres4), (long long )__retres4);
  __CrestReturn(633);
#line 300
  return (__retres4);
  }
}
}
#line 311
void subline(char *lin , char *pat , char *sub ) ;
#line 313 "replace.c"
bool locate(character c , char *pat , int offset ) 
{ 
  int i ;
  bool flag ;
  char *mem_6 ;
  char *mem_7 ;

  {
  __CrestCall(636, 13);
  __CrestStore(635, (unsigned long )(& offset));
  __CrestStore(634, (unsigned long )(& c));
  __CrestLoad(637, (unsigned long )0, (long long )((bool )0));
  __CrestStore(638, (unsigned long )(& flag));
#line 322
  flag = (bool )0;
#line 323
  mem_6 = pat + offset;
  __CrestLoad(641, (unsigned long )(& offset), (long long )offset);
  __CrestLoad(640, (unsigned long )mem_6, (long long )*mem_6);
  __CrestApply2(639, 0, (long long )(offset + (int )*mem_6));
  __CrestStore(642, (unsigned long )(& i));
#line 323
  i = offset + (int )*mem_6;
  {
#line 324
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(645, (unsigned long )(& i), (long long )i);
    __CrestLoad(644, (unsigned long )(& offset), (long long )offset);
    __CrestApply2(643, 14, (long long )(i > offset));
#line 324
    if (i > offset) {
      __CrestBranch(646, 247, 1);

    } else {
      __CrestBranch(647, 248, 0);
#line 324
      goto while_break;
    }
    }
    {
#line 326
    mem_7 = pat + i;
    {
    __CrestLoad(650, (unsigned long )(& c), (long long )c);
    __CrestLoad(649, (unsigned long )mem_7, (long long )*mem_7);
    __CrestApply2(648, 12, (long long )((int )c == (int )*mem_7));
#line 326
    if ((int )c == (int )*mem_7) {
      __CrestBranch(651, 252, 1);
      __CrestLoad(653, (unsigned long )0, (long long )((bool )1));
      __CrestStore(654, (unsigned long )(& flag));
#line 327
      flag = (bool )1;
      __CrestLoad(655, (unsigned long )(& offset), (long long )offset);
      __CrestStore(656, (unsigned long )(& i));
#line 328
      i = offset;
    } else {
      __CrestBranch(652, 253, 0);
      __CrestLoad(659, (unsigned long )(& i), (long long )i);
      __CrestLoad(658, (unsigned long )0, (long long )1);
      __CrestApply2(657, 1, (long long )(i - 1));
      __CrestStore(660, (unsigned long )(& i));
#line 330
      i --;
    }
    }
    }
  }
  while_break: /* CIL Label */ ;
  }
  {
  __CrestLoad(661, (unsigned long )(& flag), (long long )flag);
  __CrestReturn(662);
#line 332
  return (flag);
  }
}
}
#line 335 "replace.c"
bool omatch(char *lin , int *i , char *pat , int j ) 
{ 
  char advance ;
  bool result ;
  bool tmp ;
  bool tmp___0 ;
  bool tmp___1 ;
  char *mem_10 ;
  char *mem_11 ;
  char *mem_12 ;
  char *mem_13 ;
  char *mem_14 ;
  char *mem_15 ;
  char *mem_16 ;
  char *mem_17 ;
  char *mem_18 ;
  char *mem_19 ;
  char *mem_20 ;

  {
  __CrestCall(664, 14);
  __CrestStore(663, (unsigned long )(& j));
  __CrestLoad(665, (unsigned long )0, (long long )(char)-1);
  __CrestStore(666, (unsigned long )(& advance));
#line 345
  advance = (char)-1;
  {
#line 346
  mem_10 = lin + *i;
  {
  __CrestLoad(669, (unsigned long )mem_10, (long long )*mem_10);
  __CrestLoad(668, (unsigned long )0, (long long )0);
  __CrestApply2(667, 12, (long long )((int )*mem_10 == 0));
#line 346
  if ((int )*mem_10 == 0) {
    __CrestBranch(670, 260, 1);
    __CrestLoad(672, (unsigned long )0, (long long )((bool )0));
    __CrestStore(673, (unsigned long )(& result));
#line 347
    result = (bool )0;
  } else {
    __CrestBranch(671, 261, 0);
#line 350
    mem_11 = pat + j;
    __CrestLoad(674, (unsigned long )mem_11, (long long )*mem_11);
#line 350
    tmp___1 = in_pat_set(*mem_11);
    __CrestHandleReturn(676, (long long )tmp___1);
    __CrestStore(675, (unsigned long )(& tmp___1));
    {
    __CrestLoad(679, (unsigned long )(& tmp___1), (long long )tmp___1);
    __CrestLoad(678, (unsigned long )0, (long long )0);
    __CrestApply2(677, 13, (long long )(tmp___1 != 0));
#line 350
    if (tmp___1 != 0) {
      __CrestBranch(680, 263, 1);
      {
#line 356
      mem_12 = pat + j;
      {
      {
      __CrestLoad(684, (unsigned long )mem_12, (long long )*mem_12);
      __CrestLoad(683, (unsigned long )0, (long long )99);
      __CrestApply2(682, 12, (long long )((int )*mem_12 == 99));
#line 358
      if ((int )*mem_12 == 99) {
        __CrestBranch(685, 267, 1);
#line 358
        goto case_99;
      } else {
        __CrestBranch(686, 268, 0);

      }
      }
      {
      __CrestLoad(689, (unsigned long )mem_12, (long long )*mem_12);
      __CrestLoad(688, (unsigned long )0, (long long )37);
      __CrestApply2(687, 12, (long long )((int )*mem_12 == 37));
#line 362
      if ((int )*mem_12 == 37) {
        __CrestBranch(690, 270, 1);
#line 362
        goto case_37;
      } else {
        __CrestBranch(691, 271, 0);

      }
      }
      {
      __CrestLoad(694, (unsigned long )mem_12, (long long )*mem_12);
      __CrestLoad(693, (unsigned long )0, (long long )63);
      __CrestApply2(692, 12, (long long )((int )*mem_12 == 63));
#line 366
      if ((int )*mem_12 == 63) {
        __CrestBranch(695, 273, 1);
#line 366
        goto case_63;
      } else {
        __CrestBranch(696, 274, 0);

      }
      }
      {
      __CrestLoad(699, (unsigned long )mem_12, (long long )*mem_12);
      __CrestLoad(698, (unsigned long )0, (long long )36);
      __CrestApply2(697, 12, (long long )((int )*mem_12 == 36));
#line 370
      if ((int )*mem_12 == 36) {
        __CrestBranch(700, 276, 1);
#line 370
        goto case_36;
      } else {
        __CrestBranch(701, 277, 0);

      }
      }
      {
      __CrestLoad(704, (unsigned long )mem_12, (long long )*mem_12);
      __CrestLoad(703, (unsigned long )0, (long long )91);
      __CrestApply2(702, 12, (long long )((int )*mem_12 == 91));
#line 374
      if ((int )*mem_12 == 91) {
        __CrestBranch(705, 279, 1);
#line 374
        goto case_91;
      } else {
        __CrestBranch(706, 280, 0);

      }
      }
      {
      __CrestLoad(709, (unsigned long )mem_12, (long long )*mem_12);
      __CrestLoad(708, (unsigned long )0, (long long )33);
      __CrestApply2(707, 12, (long long )((int )*mem_12 == 33));
#line 378
      if ((int )*mem_12 == 33) {
        __CrestBranch(710, 282, 1);
#line 378
        goto case_33;
      } else {
        __CrestBranch(711, 283, 0);

      }
      }
#line 382
      goto switch_default;
      case_99: /* CIL Label */ 
      {
#line 359
      mem_13 = lin + *i;
#line 359
      mem_14 = pat + (j + 1);
      {
      __CrestLoad(714, (unsigned long )mem_13, (long long )*mem_13);
      __CrestLoad(713, (unsigned long )mem_14, (long long )*mem_14);
      __CrestApply2(712, 12, (long long )((int )*mem_13 == (int )*mem_14));
#line 359
      if ((int )*mem_13 == (int )*mem_14) {
        __CrestBranch(715, 288, 1);
        __CrestLoad(717, (unsigned long )0, (long long )(char)1);
        __CrestStore(718, (unsigned long )(& advance));
#line 360
        advance = (char)1;
      } else {
        __CrestBranch(716, 289, 0);

      }
      }
      }
#line 361
      goto switch_break;
      case_37: /* CIL Label */ 
      {
      __CrestLoad(721, (unsigned long )i, (long long )*i);
      __CrestLoad(720, (unsigned long )0, (long long )0);
      __CrestApply2(719, 12, (long long )(*i == 0));
#line 363
      if (*i == 0) {
        __CrestBranch(722, 292, 1);
        __CrestLoad(724, (unsigned long )0, (long long )(char)0);
        __CrestStore(725, (unsigned long )(& advance));
#line 364
        advance = (char)0;
      } else {
        __CrestBranch(723, 293, 0);

      }
      }
#line 365
      goto switch_break;
      case_63: /* CIL Label */ 
      {
#line 367
      mem_15 = lin + *i;
      {
      __CrestLoad(728, (unsigned long )mem_15, (long long )*mem_15);
      __CrestLoad(727, (unsigned long )0, (long long )10);
      __CrestApply2(726, 13, (long long )((int )*mem_15 != 10));
#line 367
      if ((int )*mem_15 != 10) {
        __CrestBranch(729, 298, 1);
        __CrestLoad(731, (unsigned long )0, (long long )(char)1);
        __CrestStore(732, (unsigned long )(& advance));
#line 368
        advance = (char)1;
      } else {
        __CrestBranch(730, 299, 0);

      }
      }
      }
#line 369
      goto switch_break;
      case_36: /* CIL Label */ 
      {
#line 371
      mem_16 = lin + *i;
      {
      __CrestLoad(735, (unsigned long )mem_16, (long long )*mem_16);
      __CrestLoad(734, (unsigned long )0, (long long )10);
      __CrestApply2(733, 12, (long long )((int )*mem_16 == 10));
#line 371
      if ((int )*mem_16 == 10) {
        __CrestBranch(736, 304, 1);
        __CrestLoad(738, (unsigned long )0, (long long )(char)0);
        __CrestStore(739, (unsigned long )(& advance));
#line 372
        advance = (char)0;
      } else {
        __CrestBranch(737, 305, 0);

      }
      }
      }
#line 373
      goto switch_break;
      case_91: /* CIL Label */ 
#line 375
      mem_17 = lin + *i;
      __CrestLoad(740, (unsigned long )mem_17, (long long )*mem_17);
      __CrestLoad(743, (unsigned long )(& j), (long long )j);
      __CrestLoad(742, (unsigned long )0, (long long )1);
      __CrestApply2(741, 0, (long long )(j + 1));
#line 375
      tmp = locate(*mem_17, pat, j + 1);
      __CrestHandleReturn(745, (long long )tmp);
      __CrestStore(744, (unsigned long )(& tmp));
      {
      __CrestLoad(748, (unsigned long )(& tmp), (long long )tmp);
      __CrestLoad(747, (unsigned long )0, (long long )0);
      __CrestApply2(746, 13, (long long )(tmp != 0));
#line 375
      if (tmp != 0) {
        __CrestBranch(749, 309, 1);
        __CrestLoad(751, (unsigned long )0, (long long )(char)1);
        __CrestStore(752, (unsigned long )(& advance));
#line 376
        advance = (char)1;
      } else {
        __CrestBranch(750, 310, 0);

      }
      }
#line 377
      goto switch_break;
      case_33: /* CIL Label */ 
      {
#line 379
      mem_18 = lin + *i;
      {
      __CrestLoad(755, (unsigned long )mem_18, (long long )*mem_18);
      __CrestLoad(754, (unsigned long )0, (long long )10);
      __CrestApply2(753, 13, (long long )((int )*mem_18 != 10));
#line 379
      if ((int )*mem_18 != 10) {
        __CrestBranch(756, 315, 1);
#line 379
        mem_19 = lin + *i;
        __CrestLoad(758, (unsigned long )mem_19, (long long )*mem_19);
        __CrestLoad(761, (unsigned long )(& j), (long long )j);
        __CrestLoad(760, (unsigned long )0, (long long )1);
        __CrestApply2(759, 0, (long long )(j + 1));
#line 379
        tmp___0 = locate(*mem_19, pat, j + 1);
        __CrestHandleReturn(763, (long long )tmp___0);
        __CrestStore(762, (unsigned long )(& tmp___0));
        {
        __CrestLoad(766, (unsigned long )(& tmp___0), (long long )tmp___0);
        __CrestLoad(765, (unsigned long )0, (long long )0);
        __CrestApply2(764, 13, (long long )(tmp___0 != 0));
#line 379
        if (tmp___0 != 0) {
          __CrestBranch(767, 317, 1);

        } else {
          __CrestBranch(768, 318, 0);
          __CrestLoad(769, (unsigned long )0, (long long )(char)1);
          __CrestStore(770, (unsigned long )(& advance));
#line 380
          advance = (char)1;
        }
        }
      } else {
        __CrestBranch(757, 319, 0);

      }
      }
      }
#line 381
      goto switch_break;
      switch_default: /* CIL Label */ 
#line 383
      mem_20 = pat + j;
      __CrestLoad(771, (unsigned long )mem_20, (long long )*mem_20);
#line 383
      Caseerror((int )*mem_20);
      __CrestClearStack(772);
      switch_break: /* CIL Label */ ;
      }
      }
    } else {
      __CrestBranch(681, 323, 0);
#line 352
      fprintf((FILE * __restrict  )stdout, (char const   * __restrict  )"in omatch: can\'t happen\n");
      __CrestClearStack(773);
#line 353
      abort();
      __CrestClearStack(774);
    }
    }
  }
  }
  }
  {
  __CrestLoad(777, (unsigned long )(& advance), (long long )advance);
  __CrestLoad(776, (unsigned long )0, (long long )0);
  __CrestApply2(775, 17, (long long )((int )advance >= 0));
#line 387
  if ((int )advance >= 0) {
    __CrestBranch(778, 325, 1);
    __CrestLoad(782, (unsigned long )i, (long long )*i);
    __CrestLoad(781, (unsigned long )(& advance), (long long )advance);
    __CrestApply2(780, 0, (long long )(*i + (int )advance));
    __CrestStore(783, (unsigned long )i);
#line 389
    *i += (int )advance;
    __CrestLoad(784, (unsigned long )0, (long long )((bool )1));
    __CrestStore(785, (unsigned long )(& result));
#line 390
    result = (bool )1;
  } else {
    __CrestBranch(779, 326, 0);
    __CrestLoad(786, (unsigned long )0, (long long )((bool )0));
    __CrestStore(787, (unsigned long )(& result));
#line 392
    result = (bool )0;
  }
  }
  {
  __CrestLoad(788, (unsigned long )(& result), (long long )result);
  __CrestReturn(789);
#line 393
  return (result);
  }
}
}
#line 396 "replace.c"
int patsize(char *pat , int n ) 
{ 
  int size ;
  bool tmp ;
  char *mem_5 ;
  char *mem_6 ;
  char *mem_7 ;
  char *mem_8 ;

  {
  __CrestCall(791, 15);
  __CrestStore(790, (unsigned long )(& n));
#line 402
  mem_5 = pat + n;
  __CrestLoad(792, (unsigned long )mem_5, (long long )*mem_5);
#line 402
  tmp = in_pat_set(*mem_5);
  __CrestHandleReturn(794, (long long )tmp);
  __CrestStore(793, (unsigned long )(& tmp));
  {
  __CrestLoad(797, (unsigned long )(& tmp), (long long )tmp);
  __CrestLoad(796, (unsigned long )0, (long long )0);
  __CrestApply2(795, 13, (long long )(tmp != 0));
#line 402
  if (tmp != 0) {
    __CrestBranch(798, 330, 1);
    {
#line 406
    mem_6 = pat + n;
    {
    {
    __CrestLoad(802, (unsigned long )mem_6, (long long )*mem_6);
    __CrestLoad(801, (unsigned long )0, (long long )99);
    __CrestApply2(800, 12, (long long )((int )*mem_6 == 99));
#line 408
    if ((int )*mem_6 == 99) {
      __CrestBranch(803, 334, 1);
#line 408
      goto case_99;
    } else {
      __CrestBranch(804, 335, 0);

    }
    }
    {
    __CrestLoad(807, (unsigned long )mem_6, (long long )*mem_6);
    __CrestLoad(806, (unsigned long )0, (long long )63);
    __CrestApply2(805, 12, (long long )((int )*mem_6 == 63));
#line 410
    if ((int )*mem_6 == 63) {
      __CrestBranch(808, 337, 1);
#line 410
      goto case_63;
    } else {
      __CrestBranch(809, 338, 0);

    }
    }
    {
    __CrestLoad(812, (unsigned long )mem_6, (long long )*mem_6);
    __CrestLoad(811, (unsigned long )0, (long long )36);
    __CrestApply2(810, 12, (long long )((int )*mem_6 == 36));
#line 410
    if ((int )*mem_6 == 36) {
      __CrestBranch(813, 340, 1);
#line 410
      goto case_63;
    } else {
      __CrestBranch(814, 341, 0);

    }
    }
    {
    __CrestLoad(817, (unsigned long )mem_6, (long long )*mem_6);
    __CrestLoad(816, (unsigned long )0, (long long )37);
    __CrestApply2(815, 12, (long long )((int )*mem_6 == 37));
#line 410
    if ((int )*mem_6 == 37) {
      __CrestBranch(818, 343, 1);
#line 410
      goto case_63;
    } else {
      __CrestBranch(819, 344, 0);

    }
    }
    {
    __CrestLoad(822, (unsigned long )mem_6, (long long )*mem_6);
    __CrestLoad(821, (unsigned long )0, (long long )33);
    __CrestApply2(820, 12, (long long )((int )*mem_6 == 33));
#line 413
    if ((int )*mem_6 == 33) {
      __CrestBranch(823, 346, 1);
#line 413
      goto case_33;
    } else {
      __CrestBranch(824, 347, 0);

    }
    }
    {
    __CrestLoad(827, (unsigned long )mem_6, (long long )*mem_6);
    __CrestLoad(826, (unsigned long )0, (long long )91);
    __CrestApply2(825, 12, (long long )((int )*mem_6 == 91));
#line 413
    if ((int )*mem_6 == 91) {
      __CrestBranch(828, 349, 1);
#line 413
      goto case_33;
    } else {
      __CrestBranch(829, 350, 0);

    }
    }
    {
    __CrestLoad(832, (unsigned long )mem_6, (long long )*mem_6);
    __CrestLoad(831, (unsigned long )0, (long long )42);
    __CrestApply2(830, 12, (long long )((int )*mem_6 == 42));
#line 416
    if ((int )*mem_6 == 42) {
      __CrestBranch(833, 352, 1);
#line 416
      goto case_42;
    } else {
      __CrestBranch(834, 353, 0);

    }
    }
#line 419
    goto switch_default;
    case_99: /* CIL Label */ 
    __CrestLoad(835, (unsigned long )0, (long long )2);
    __CrestStore(836, (unsigned long )(& size));
#line 408
    size = 2;
#line 408
    goto switch_break;
    case_63: /* CIL Label */ 
    case_36: /* CIL Label */ 
    case_37: /* CIL Label */ 
    __CrestLoad(837, (unsigned long )0, (long long )1);
    __CrestStore(838, (unsigned long )(& size));
#line 411
    size = 1;
#line 412
    goto switch_break;
    case_33: /* CIL Label */ 
    case_91: /* CIL Label */ 
#line 414
    mem_7 = pat + (n + 1);
    __CrestLoad(841, (unsigned long )mem_7, (long long )*mem_7);
    __CrestLoad(840, (unsigned long )0, (long long )2);
    __CrestApply2(839, 0, (long long )((int )*mem_7 + 2));
    __CrestStore(842, (unsigned long )(& size));
#line 414
    size = (int )*mem_7 + 2;
#line 415
    goto switch_break;
    case_42: /* CIL Label */ 
    __CrestLoad(843, (unsigned long )0, (long long )1);
    __CrestStore(844, (unsigned long )(& size));
#line 417
    size = 1;
#line 418
    goto switch_break;
    switch_default: /* CIL Label */ 
#line 420
    mem_8 = pat + n;
    __CrestLoad(845, (unsigned long )mem_8, (long long )*mem_8);
#line 420
    Caseerror((int )*mem_8);
    __CrestClearStack(846);
    switch_break: /* CIL Label */ ;
    }
    }
  } else {
    __CrestBranch(799, 365, 0);
#line 403
    fprintf((FILE * __restrict  )stdout, (char const   * __restrict  )"in patsize: can\'t happen\n");
    __CrestClearStack(847);
#line 404
    abort();
    __CrestClearStack(848);
  }
  }
  {
  __CrestLoad(849, (unsigned long )(& size), (long long )size);
  __CrestReturn(850);
#line 422
  return (size);
  }
}
}
#line 425 "replace.c"
int amatch(char *lin , int offset , char *pat , int j ) 
{ 
  int i ;
  int k ;
  bool result ;
  bool done ;
  int tmp ;
  int tmp___0 ;
  int tmp___1 ;
  char *mem_12 ;
  char *mem_13 ;
  char *mem_14 ;

  {
  __CrestCall(853, 16);
  __CrestStore(852, (unsigned long )(& j));
  __CrestStore(851, (unsigned long )(& offset));
  __CrestLoad(854, (unsigned long )0, (long long )((bool )0));
  __CrestStore(855, (unsigned long )(& done));
#line 435
  done = (bool )0;
  {
#line 436
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(858, (unsigned long )(& done), (long long )done);
    __CrestLoad(857, (unsigned long )0, (long long )0);
    __CrestApply2(856, 12, (long long )(done == 0));
#line 436
    if (done == 0) {
      __CrestBranch(859, 372, 1);
      {
#line 436
      mem_12 = pat + j;
      {
      __CrestLoad(863, (unsigned long )mem_12, (long long )*mem_12);
      __CrestLoad(862, (unsigned long )0, (long long )0);
      __CrestApply2(861, 13, (long long )((int )*mem_12 != 0));
#line 436
      if ((int )*mem_12 != 0) {
        __CrestBranch(864, 375, 1);

      } else {
        __CrestBranch(865, 376, 0);
#line 436
        goto while_break;
      }
      }
      }
    } else {
      __CrestBranch(860, 377, 0);
#line 436
      goto while_break;
    }
    }
    {
#line 437
    mem_13 = pat + j;
    {
    __CrestLoad(868, (unsigned long )mem_13, (long long )*mem_13);
    __CrestLoad(867, (unsigned long )0, (long long )42);
    __CrestApply2(866, 12, (long long )((int )*mem_13 == 42));
#line 437
    if ((int )*mem_13 == 42) {
      __CrestBranch(869, 381, 1);
      __CrestLoad(871, (unsigned long )(& j), (long long )j);
#line 438
      tmp = patsize(pat, j);
      __CrestHandleReturn(873, (long long )tmp);
      __CrestStore(872, (unsigned long )(& tmp));
      __CrestLoad(876, (unsigned long )(& j), (long long )j);
      __CrestLoad(875, (unsigned long )(& tmp), (long long )tmp);
      __CrestApply2(874, 0, (long long )(j + tmp));
      __CrestStore(877, (unsigned long )(& j));
#line 438
      j += tmp;
      __CrestLoad(878, (unsigned long )(& offset), (long long )offset);
      __CrestStore(879, (unsigned long )(& i));
#line 439
      i = offset;
      {
#line 440
      while (1) {
        while_continue___0: /* CIL Label */ ;
        {
        __CrestLoad(882, (unsigned long )(& done), (long long )done);
        __CrestLoad(881, (unsigned long )0, (long long )0);
        __CrestApply2(880, 12, (long long )(done == 0));
#line 440
        if (done == 0) {
          __CrestBranch(883, 386, 1);
          {
#line 440
          mem_14 = lin + i;
          {
          __CrestLoad(887, (unsigned long )mem_14, (long long )*mem_14);
          __CrestLoad(886, (unsigned long )0, (long long )0);
          __CrestApply2(885, 13, (long long )((int )*mem_14 != 0));
#line 440
          if ((int )*mem_14 != 0) {
            __CrestBranch(888, 389, 1);

          } else {
            __CrestBranch(889, 390, 0);
#line 440
            goto while_break___0;
          }
          }
          }
        } else {
          __CrestBranch(884, 391, 0);
#line 440
          goto while_break___0;
        }
        }
        __CrestLoad(890, (unsigned long )(& j), (long long )j);
#line 441
        result = omatch(lin, & i, pat, j);
        __CrestHandleReturn(892, (long long )result);
        __CrestStore(891, (unsigned long )(& result));
        {
        __CrestLoad(895, (unsigned long )(& result), (long long )result);
        __CrestLoad(894, (unsigned long )0, (long long )0);
        __CrestApply2(893, 12, (long long )(result == 0));
#line 442
        if (result == 0) {
          __CrestBranch(896, 394, 1);
          __CrestLoad(898, (unsigned long )0, (long long )((bool )1));
          __CrestStore(899, (unsigned long )(& done));
#line 443
          done = (bool )1;
        } else {
          __CrestBranch(897, 395, 0);

        }
        }
      }
      while_break___0: /* CIL Label */ ;
      }
      __CrestLoad(900, (unsigned long )0, (long long )((bool )0));
      __CrestStore(901, (unsigned long )(& done));
#line 445
      done = (bool )0;
      {
#line 446
      while (1) {
        while_continue___1: /* CIL Label */ ;
        {
        __CrestLoad(904, (unsigned long )(& done), (long long )done);
        __CrestLoad(903, (unsigned long )0, (long long )0);
        __CrestApply2(902, 12, (long long )(done == 0));
#line 446
        if (done == 0) {
          __CrestBranch(905, 402, 1);
          {
          __CrestLoad(909, (unsigned long )(& i), (long long )i);
          __CrestLoad(908, (unsigned long )(& offset), (long long )offset);
          __CrestApply2(907, 17, (long long )(i >= offset));
#line 446
          if (i >= offset) {
            __CrestBranch(910, 403, 1);

          } else {
            __CrestBranch(911, 404, 0);
#line 446
            goto while_break___1;
          }
          }
        } else {
          __CrestBranch(906, 405, 0);
#line 446
          goto while_break___1;
        }
        }
        __CrestLoad(912, (unsigned long )(& j), (long long )j);
#line 447
        tmp___0 = patsize(pat, j);
        __CrestHandleReturn(914, (long long )tmp___0);
        __CrestStore(913, (unsigned long )(& tmp___0));
        __CrestLoad(915, (unsigned long )(& i), (long long )i);
        __CrestLoad(918, (unsigned long )(& j), (long long )j);
        __CrestLoad(917, (unsigned long )(& tmp___0), (long long )tmp___0);
        __CrestApply2(916, 0, (long long )(j + tmp___0));
#line 447
        k = amatch(lin, i, pat, j + tmp___0);
        __CrestHandleReturn(920, (long long )k);
        __CrestStore(919, (unsigned long )(& k));
        {
        __CrestLoad(923, (unsigned long )(& k), (long long )k);
        __CrestLoad(922, (unsigned long )0, (long long )0);
        __CrestApply2(921, 17, (long long )(k >= 0));
#line 448
        if (k >= 0) {
          __CrestBranch(924, 408, 1);
          __CrestLoad(926, (unsigned long )0, (long long )((bool )1));
          __CrestStore(927, (unsigned long )(& done));
#line 449
          done = (bool )1;
        } else {
          __CrestBranch(925, 409, 0);
          __CrestLoad(930, (unsigned long )(& i), (long long )i);
          __CrestLoad(929, (unsigned long )0, (long long )1);
          __CrestApply2(928, 1, (long long )(i - 1));
          __CrestStore(931, (unsigned long )(& i));
#line 451
          i --;
        }
        }
      }
      while_break___1: /* CIL Label */ ;
      }
      __CrestLoad(932, (unsigned long )(& k), (long long )k);
      __CrestStore(933, (unsigned long )(& offset));
#line 453
      offset = k;
      __CrestLoad(934, (unsigned long )0, (long long )((bool )1));
      __CrestStore(935, (unsigned long )(& done));
#line 454
      done = (bool )1;
    } else {
      __CrestBranch(870, 412, 0);
      __CrestLoad(936, (unsigned long )(& j), (long long )j);
#line 456
      result = omatch(lin, & offset, pat, j);
      __CrestHandleReturn(938, (long long )result);
      __CrestStore(937, (unsigned long )(& result));
      {
      __CrestLoad(941, (unsigned long )(& result), (long long )result);
      __CrestLoad(940, (unsigned long )0, (long long )0);
      __CrestApply2(939, 12, (long long )(result == 0));
#line 457
      if (result == 0) {
        __CrestBranch(942, 414, 1);
        __CrestLoad(944, (unsigned long )0, (long long )-1);
        __CrestStore(945, (unsigned long )(& offset));
#line 458
        offset = -1;
        __CrestLoad(946, (unsigned long )0, (long long )((bool )1));
        __CrestStore(947, (unsigned long )(& done));
#line 459
        done = (bool )1;
      } else {
        __CrestBranch(943, 415, 0);
        __CrestLoad(948, (unsigned long )(& j), (long long )j);
#line 461
        tmp___1 = patsize(pat, j);
        __CrestHandleReturn(950, (long long )tmp___1);
        __CrestStore(949, (unsigned long )(& tmp___1));
        __CrestLoad(953, (unsigned long )(& j), (long long )j);
        __CrestLoad(952, (unsigned long )(& tmp___1), (long long )tmp___1);
        __CrestApply2(951, 0, (long long )(j + tmp___1));
        __CrestStore(954, (unsigned long )(& j));
#line 461
        j += tmp___1;
      }
      }
    }
    }
    }
  }
  while_break: /* CIL Label */ ;
  }
  {
  __CrestLoad(955, (unsigned long )(& offset), (long long )offset);
  __CrestReturn(956);
#line 463
  return (offset);
  }
}
}
#line 466 "replace.c"
void putsub(char *lin , int s1 , int s2 , char *sub ) 
{ 
  int i ;
  int j ;
  char *mem_7 ;
  char *mem_8 ;
  char *mem_9 ;
  char *mem_10 ;

  {
  __CrestCall(959, 17);
  __CrestStore(958, (unsigned long )(& s2));
  __CrestStore(957, (unsigned long )(& s1));
  __CrestLoad(960, (unsigned long )0, (long long )0);
  __CrestStore(961, (unsigned long )(& i));
#line 475
  i = 0;
  {
#line 476
  while (1) {
    while_continue: /* CIL Label */ ;
    {
#line 476
    mem_7 = sub + i;
    {
    __CrestLoad(964, (unsigned long )mem_7, (long long )*mem_7);
    __CrestLoad(963, (unsigned long )0, (long long )0);
    __CrestApply2(962, 13, (long long )((int )*mem_7 != 0));
#line 476
    if ((int )*mem_7 != 0) {
      __CrestBranch(965, 425, 1);

    } else {
      __CrestBranch(966, 426, 0);
#line 476
      goto while_break;
    }
    }
    }
    {
#line 477
    mem_8 = sub + i;
    {
    __CrestLoad(969, (unsigned long )mem_8, (long long )*mem_8);
    __CrestLoad(968, (unsigned long )0, (long long )-1);
    __CrestApply2(967, 12, (long long )((int )*mem_8 == -1));
#line 477
    if ((int )*mem_8 == -1) {
      __CrestBranch(970, 430, 1);
      __CrestLoad(972, (unsigned long )(& s1), (long long )s1);
      __CrestStore(973, (unsigned long )(& j));
#line 478
      j = s1;
      {
#line 478
      while (1) {
        while_continue___0: /* CIL Label */ ;
        {
        __CrestLoad(976, (unsigned long )(& j), (long long )j);
        __CrestLoad(975, (unsigned long )(& s2), (long long )s2);
        __CrestApply2(974, 16, (long long )(j < s2));
#line 478
        if (j < s2) {
          __CrestBranch(977, 435, 1);

        } else {
          __CrestBranch(978, 436, 0);
#line 478
          goto while_break___0;
        }
        }
#line 480
        mem_9 = lin + j;
        __CrestLoad(979, (unsigned long )mem_9, (long long )*mem_9);
#line 480
        fputc((int )*mem_9, stdout);
        __CrestClearStack(980);
        __CrestLoad(983, (unsigned long )(& j), (long long )j);
        __CrestLoad(982, (unsigned long )0, (long long )1);
        __CrestApply2(981, 0, (long long )(j + 1));
        __CrestStore(984, (unsigned long )(& j));
#line 478
        j ++;
      }
      while_break___0: /* CIL Label */ ;
      }
    } else {
      __CrestBranch(971, 439, 0);
#line 484
      mem_10 = sub + i;
      __CrestLoad(985, (unsigned long )mem_10, (long long )*mem_10);
#line 484
      fputc((int )*mem_10, stdout);
      __CrestClearStack(986);
    }
    }
    }
    __CrestLoad(989, (unsigned long )(& i), (long long )i);
    __CrestLoad(988, (unsigned long )0, (long long )1);
    __CrestApply2(987, 0, (long long )(i + 1));
    __CrestStore(990, (unsigned long )(& i));
#line 486
    i ++;
  }
  while_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(991);
#line 466
  return;
  }
}
}
#line 490 "replace.c"
void subline(char *lin , char *pat , char *sub ) 
{ 
  int i ;
  int lastm ;
  int m ;
  char *mem_7 ;
  char *mem_8 ;
  char *mem_9 ;

  {
  __CrestCall(992, 18);

  __CrestLoad(993, (unsigned long )0, (long long )-1);
  __CrestStore(994, (unsigned long )(& lastm));
#line 498
  lastm = -1;
  __CrestLoad(995, (unsigned long )0, (long long )0);
  __CrestStore(996, (unsigned long )(& i));
#line 499
  i = 0;
  {
#line 500
  while (1) {
    while_continue: /* CIL Label */ ;
    {
#line 500
    mem_7 = lin + i;
    {
    __CrestLoad(999, (unsigned long )mem_7, (long long )*mem_7);
    __CrestLoad(998, (unsigned long )0, (long long )0);
    __CrestApply2(997, 13, (long long )((int )*mem_7 != 0));
#line 500
    if ((int )*mem_7 != 0) {
      __CrestBranch(1000, 451, 1);

    } else {
      __CrestBranch(1001, 452, 0);
#line 500
      goto while_break;
    }
    }
    }
    __CrestLoad(1002, (unsigned long )(& i), (long long )i);
    __CrestLoad(1003, (unsigned long )0, (long long )0);
#line 502
    m = amatch(lin, i, pat, 0);
    __CrestHandleReturn(1005, (long long )m);
    __CrestStore(1004, (unsigned long )(& m));
    {
    __CrestLoad(1008, (unsigned long )(& m), (long long )m);
    __CrestLoad(1007, (unsigned long )0, (long long )0);
    __CrestApply2(1006, 17, (long long )(m >= 0));
#line 503
    if (m >= 0) {
      __CrestBranch(1009, 455, 1);
      {
      __CrestLoad(1013, (unsigned long )(& lastm), (long long )lastm);
      __CrestLoad(1012, (unsigned long )(& m), (long long )m);
      __CrestApply2(1011, 13, (long long )(lastm != m));
#line 503
      if (lastm != m) {
        __CrestBranch(1014, 456, 1);
        __CrestLoad(1016, (unsigned long )(& i), (long long )i);
        __CrestLoad(1017, (unsigned long )(& m), (long long )m);
#line 504
        putsub(lin, i, m, sub);
        __CrestClearStack(1018);
        __CrestLoad(1019, (unsigned long )(& m), (long long )m);
        __CrestStore(1020, (unsigned long )(& lastm));
#line 505
        lastm = m;
      } else {
        __CrestBranch(1015, 457, 0);

      }
      }
    } else {
      __CrestBranch(1010, 458, 0);

    }
    }
    {
    __CrestLoad(1023, (unsigned long )(& m), (long long )m);
    __CrestLoad(1022, (unsigned long )0, (long long )-1);
    __CrestApply2(1021, 12, (long long )(m == -1));
#line 507
    if (m == -1) {
      __CrestBranch(1024, 460, 1);
#line 508
      mem_8 = lin + i;
      __CrestLoad(1026, (unsigned long )mem_8, (long long )*mem_8);
#line 508
      fputc((int )*mem_8, stdout);
      __CrestClearStack(1027);
      __CrestLoad(1030, (unsigned long )(& i), (long long )i);
      __CrestLoad(1029, (unsigned long )0, (long long )1);
      __CrestApply2(1028, 0, (long long )(i + 1));
      __CrestStore(1031, (unsigned long )(& i));
#line 509
      i ++;
    } else {
      __CrestBranch(1025, 461, 0);
      {
      __CrestLoad(1034, (unsigned long )(& m), (long long )m);
      __CrestLoad(1033, (unsigned long )(& i), (long long )i);
      __CrestApply2(1032, 12, (long long )(m == i));
#line 507
      if (m == i) {
        __CrestBranch(1035, 462, 1);
#line 508
        mem_9 = lin + i;
        __CrestLoad(1037, (unsigned long )mem_9, (long long )*mem_9);
#line 508
        fputc((int )*mem_9, stdout);
        __CrestClearStack(1038);
        __CrestLoad(1041, (unsigned long )(& i), (long long )i);
        __CrestLoad(1040, (unsigned long )0, (long long )1);
        __CrestApply2(1039, 0, (long long )(i + 1));
        __CrestStore(1042, (unsigned long )(& i));
#line 509
        i ++;
      } else {
        __CrestBranch(1036, 463, 0);
        __CrestLoad(1043, (unsigned long )(& m), (long long )m);
        __CrestStore(1044, (unsigned long )(& i));
#line 511
        i = m;
      }
      }
    }
    }
  }
  while_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(1045);
#line 490
  return;
  }
}
}
#line 515 "replace.c"
void change(char *pat , char *sub ) 
{ 
  string line ;
  bool result ;

  {
  __CrestCall(1046, 19);

  __CrestLoad(1047, (unsigned long )0, (long long )100);
#line 522
  result = getline2(line, 100);
  __CrestHandleReturn(1049, (long long )result);
  __CrestStore(1048, (unsigned long )(& result));
  {
  __CrestLoad(1052, (unsigned long )(& result), (long long )result);
  __CrestLoad(1051, (unsigned long )0, (long long )0);
  __CrestApply2(1050, 13, (long long )(result != 0));
#line 523
  if (result != 0) {
    __CrestBranch(1053, 469, 1);
#line 524
    subline(line, pat, sub);
    __CrestClearStack(1055);
  } else {
    __CrestBranch(1054, 470, 0);

  }
  }

  {
  __CrestReturn(1056);
#line 515
  return;
  }
}
}
#line 528 "replace.c"
int main(void) 
{ 
  string pat ;
  string sub ;
  bool result ;
  string input1 ;
  string input2 ;
  int i ;
  int tmp ;
  int __retres8 ;

  {
  __globinit_replace();
  __CrestCall(1057, 20);
  __CrestLoad(1058, (unsigned long )0, (long long )0);
  __CrestStore(1059, (unsigned long )(& i));
#line 538
  i = 0;
#line 538
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(1062, (unsigned long )(& i), (long long )i);
    __CrestLoad(1061, (unsigned long )0, (long long )9);
    __CrestApply2(1060, 16, (long long )(i < 9));
#line 538
    if (i < 9) {
      __CrestBranch(1063, 478, 1);

    } else {
      __CrestBranch(1064, 479, 0);
#line 538
      goto while_break;
    }
    }
#line 539
    __CrestChar(& input1[i]);
    __CrestLoad(1067, (unsigned long )(& i), (long long )i);
    __CrestLoad(1066, (unsigned long )0, (long long )1);
    __CrestApply2(1065, 0, (long long )(i + 1));
    __CrestStore(1068, (unsigned long )(& i));
#line 538
    i ++;
  }
  while_break: /* CIL Label */ 
  __CrestLoad(1069, (unsigned long )0, (long long )(char)0);
  __CrestStore(1070, (unsigned long )(& input1[i]));
#line 541
  input1[i] = (char)0;
#line 543
  tmp = getpat(input1, pat);
  __CrestHandleReturn(1072, (long long )tmp);
  __CrestStore(1071, (unsigned long )(& tmp));
  __CrestLoad(1073, (unsigned long )(& tmp), (long long )tmp);
  __CrestStore(1074, (unsigned long )(& result));
#line 543
  result = (bool )tmp;
  __CrestLoad(1077, (unsigned long )(& result), (long long )result);
  __CrestLoad(1076, (unsigned long )0, (long long )0);
  __CrestApply2(1075, 12, (long long )(result == 0));
#line 544
  if (result == 0) {
    __CrestBranch(1078, 484, 1);
#line 546
    fprintf((FILE * __restrict  )stdout, (char const   * __restrict  )"change: illegal \"from\" pattern\n");
    __CrestClearStack(1080);
    __CrestLoad(1081, (unsigned long )0, (long long )2);
#line 547
    exit(2);
    __CrestClearStack(1082);
  } else {
    __CrestBranch(1079, 485, 0);

  }
  __CrestLoad(1083, (unsigned long )0, (long long )0);
  __CrestStore(1084, (unsigned long )(& i));
#line 550
  i = 0;
#line 550
  while (1) {
    while_continue___0: /* CIL Label */ ;
    {
    __CrestLoad(1087, (unsigned long )(& i), (long long )i);
    __CrestLoad(1086, (unsigned long )0, (long long )9);
    __CrestApply2(1085, 16, (long long )(i < 9));
#line 550
    if (i < 9) {
      __CrestBranch(1088, 491, 1);

    } else {
      __CrestBranch(1089, 492, 0);
#line 550
      goto while_break___0;
    }
    }
#line 551
    __CrestChar(& input2[i]);
    __CrestLoad(1092, (unsigned long )(& i), (long long )i);
    __CrestLoad(1091, (unsigned long )0, (long long )1);
    __CrestApply2(1090, 0, (long long )(i + 1));
    __CrestStore(1093, (unsigned long )(& i));
#line 550
    i ++;
  }
  while_break___0: /* CIL Label */ 
  __CrestLoad(1094, (unsigned long )0, (long long )(char)0);
  __CrestStore(1095, (unsigned long )(& input2[i]));
#line 553
  input2[i] = (char)0;
#line 555
  result = getsub(input2, sub);
  __CrestHandleReturn(1097, (long long )result);
  __CrestStore(1096, (unsigned long )(& result));
  __CrestLoad(1100, (unsigned long )(& result), (long long )result);
  __CrestLoad(1099, (unsigned long )0, (long long )0);
  __CrestApply2(1098, 12, (long long )(result == 0));
#line 556
  if (result == 0) {
    __CrestBranch(1101, 497, 1);
#line 558
    fprintf((FILE * __restrict  )stdout, (char const   * __restrict  )"change: illegal \"to\" string\n");
    __CrestClearStack(1103);
    __CrestLoad(1104, (unsigned long )0, (long long )3);
#line 559
    exit(3);
    __CrestClearStack(1105);
  } else {
    __CrestBranch(1102, 498, 0);

  }
#line 562
  change(pat, sub);
  __CrestClearStack(1106);
  __CrestLoad(1107, (unsigned long )0, (long long )0);
  __CrestStore(1108, (unsigned long )(& __retres8));
#line 563
  __retres8 = 0;
  __CrestLoad(1109, (unsigned long )(& __retres8), (long long )__retres8);
  __CrestReturn(1110);
#line 528
  return (__retres8);
}
}
#line 566 "replace.c"
void Caseerror(int n ) 
{ 


  {
  __CrestCall(1112, 21);
  __CrestStore(1111, (unsigned long )(& n));
  __CrestLoad(1113, (unsigned long )(& n), (long long )n);
#line 570
  fprintf((FILE * __restrict  )stdout, (char const   * __restrict  )"Missing case limb: line %d\n",
          n);
  __CrestClearStack(1114);
  __CrestLoad(1115, (unsigned long )0, (long long )4);
#line 571
  exit(4);
  __CrestClearStack(1116);
  {
  __CrestReturn(1117);
#line 566
  return;
  }
}
}
void __globinit_replace(void) 
{ 


  {
  __CrestInit();
}
}
