/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

void print_hello(void) ;
extern int printf(char const   * __restrict  __format  , ...) ;
void print_hello(void) 
{ 


  {
  printf((char const   * __restrict  )"hello world\n");
  return;
}
}
